'use strict';
const KEY='local-delivery-v1';
// No sample people, sample money or sample requirements are shown to customers.
// The account below is replaced from the existing Aditya Studio login session.
const seed=()=>({users:{me:{name:'Login करें',balance:0}},orders:[],transactions:[]});
let state;try{state=JSON.parse(localStorage.getItem(KEY))||seed()}catch{state=seed()}
// Keep saved delivery records across code updates. Reset only truly corrupt
// storage, never a valid signed-in user's record.
if(!state||typeof state!=='object'||!state.users||!Object.keys(state.users).length){state=seed();try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
if(!Array.isArray(state.orders))state.orders=[];
if(!Array.isArray(state.transactions))state.transactions=[];
let user=state.users.me?'me':Object.keys(state.users)[0],tab='home',active=null,category='All',query='';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>'₹'+n.toLocaleString('en-IN'),total=o=>o.items+o.fee;
const held=id=>DeliveryEngine.holds(state,id),available=id=>Number(state.users[id]?.balance||0);
const mine=o=>o.owner===user||o.provider===user,icons={Groceries:'🥬',Pickup:'📦',Shopping:'🛍️',Other:'✦'},labels={open:'नई मांग',chat:'बातचीत जारी',booked:'बुक हो गया',delivering:'पुष्टि का इंतज़ार',completed:'पूरा हुआ',cancelled:'रद्द'};
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('Storage is unavailable. Keep this page open to retain this session.')}}
let toastTimer;function toast(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4000)}
function system(o,text){o.messages.push({sender:'system',text,time:new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})})}
function go(t){tab=t;active=null;render()}
function badge(o){return `<span class="badge status-${o.status}">${labels[o.status]}</span>`}
function walletCard(){const pending=Number(state.users[user]?.pendingBalance||0);return `<div class="wallet"><div class="row"><strong>आपका वॉलेट</strong><span class="wallet-symbol">▣</span></div><small>उपलब्ध रकम</small><div class="balance">${money(available(user))}</div>${pending>0?`<div class="notice" style="margin:9px 0;color:#fde68a">⏳ Recharge pending: <strong>${money(pending)}</strong><br><small>Admin verification के बाद wallet में add होगा।</small></div>`:''}<div class="escrow-row"><span>▣ रिज़र्व रकम: <strong>${money(held(user))}</strong></span><button class="text-button" data-go="wallet">लेन-देन देखें ↗</button></div><a class="btn" href="/add-money">＋ पैसा ऐड करें</a></div>`}
function card(o){return `<article class="card"><div class="row">${badge(o)}<div class="reward"><small>DELIVERY REWARD</small><strong>${money(o.fee)}</strong></div></div><div class="request-heading"><span class="category-icon">${itemEmoji(o)}</span><div><small>${esc(o.category)}</small><h3>${esc(o.title)}</h3></div></div><p class="description">${esc(o.description)}</p><div class="route"><div><span class="route-dot"></span><div><small>PICKUP / ROUTE</small><p>${esc(o.area)}</p></div></div><div><span class="route-dot destination"></span><div><small>DROP-OFF</small><p>${mine(o)?esc(o.address):'Exact address shared after acceptance'}</p></div></div></div><div class="row card-footer"><small>${esc(state.users[o.owner].name)}<br>Items estimate: ${money(o.items)}</small><button class="btn small" data-open="${o.id}">${o.owner===user?'Manage request':'View request'} ↗</button></div></article>`}
function home(){const list=state.orders.filter(o=>o.status==='open'&&(category==='All'||o.category===category)&&`${o.title} ${o.description} ${o.area}`.toLowerCase().includes(query.toLowerCase()));return `<section class="hero"><div><span class="eyebrow">A little help. A lot closer.</span><h1>Your neighbourhood.<br>Your helping hands.</h1><p>Need something picked up? Post a request, connect with someone nearby, and get it delivered.</p><button class="btn" data-go="post">＋ Post a requirement</button></div><div class="hero-art" aria-hidden="true"><div class="orbit"><span class="parcel">📦</span></div><div class="float one">✦ A little extra earning</div><div class="float two">✓ Help is just around the corner</div></div></section><div class="stats"><div class="stat"><span class="stat-icon">▤</span><div><strong>${state.orders.filter(o=>o.status==='open').length.toString().padStart(2,'0')}</strong><small>Open requirements</small></div></div><div class="stat"><span class="stat-icon">◷</span><div><strong>${state.orders.filter(o=>mine(o)&&['chat','booked','delivering'].includes(o.status)).length.toString().padStart(2,'0')}</strong><small>Your active orders</small></div></div><div class="stat"><span class="stat-icon">✓</span><div><strong>${state.orders.filter(o=>mine(o)&&o.status==='completed').length.toString().padStart(2,'0')}</strong><small>Completed deliveries</small></div></div></div><div class="workspace"><section><div class="row"><h2>Around your neighbourhood</h2><small>${list.length} requests available</small></div><input class="search" id="search" aria-label="Search requirements" placeholder="⌕ Search groceries, pickups, places…" value="${esc(query)}"><div class="filters">${['All','Groceries','Pickup','Shopping','Other'].map(c=>`<button class="chip ${category===c?'active':''}" data-category="${c}">${c==='All'?'All requests':c}</button>`).join('')}</div><div class="grid">${list.map(card).join('')||'<div class="empty">No requests here yet. Try another category or post your own.</div>'}</div></section><aside class="aside">${walletCard()}<div class="panel"><h3 style="margin-top:0">Good neighbours. Simple steps.</h3><ol class="steps"><li><div>Post what you need<small>Add your items and a delivery reward.</small></div></li><li><div>Connect & agree<small>Chat, agree on a price, then book.</small></div></li><li><div>Receive & confirm<small>Both confirm. Your helper gets paid.</small></div></li></ol><div class="notice">Your payment stays reserved until both sides confirm delivery.</div></div></aside></div>`}
function postView(){return `<button class="back" data-go="home">← Back to neighbourhood</button><div class="panel form"><span class="eyebrow">Let someone lend a hand</span><h1 style="font-size:30px">What do you need?</h1><p class="muted">Saaman ki details aur delivery reward add karein.</p><form id="postForm"><label>Requirement title<input name="title" required maxlength="100" placeholder="e.g. Weekly groceries from Birra market"></label><label>Items & instructions<textarea name="description" required rows="3" maxlength="1500" placeholder="List quantities, preferred shop and any other instructions"></textarea></label><div class="form-grid"><label>Category<select name="category">${Object.keys(icons).map(c=>`<option>${c}</option>`).join('')}</select></label><label>Pickup / shop location<input name="pickup" required maxlength="150" placeholder="Birra market"></label><label>Estimated items cost (₹)<input name="items" type="number" min="0" max="100000" step="1" required placeholder="500"></label><label>डिलीवरी का मेहनताना (₹)<input name="fee" type="number" min="1" max="100000" step="1" required placeholder="80"></label></div><label>डिलीवरी का पता<textarea name="address" required maxlength="300" rows="2" placeholder="House, street, landmark and village"></textarea></label><div class="notice">The total is items cost + delivery reward. Money is reserved when you confirm booking, and transferred only after both delivery confirmations. Exact address is shared with your selected helper.</div><button class="btn" type="submit">＋ Publish requirement</button></form></div>`}
function walletView(){return `<h2>आपका वॉलेट</h2><p class="muted">अपने पैसों और डिलीवरी का हिसाब देखें।</p><div class="detail"><div>${walletCard()}<div class="notice">Aditya Studio wallet का balance यहां दिखता है।</div><form class="panel" id="redeemCode"><label>Redeem code<input name="code" required maxlength="80" autocomplete="off" placeholder="अपना wallet code लिखें"></label><button class="btn amber">Code redeem करें</button></form><a class="btn secondary" href="/add-money" style="margin-top:10px;width:100%">＋ पैसा ऐड करें</a></div><div class="panel"><div class="row"><h3>लेन-देन का हिसाब</h3><small>Available: ${money(state.users[user].balance)}</small></div>${state.transactions.filter(t=>t.user===user).map(t=>{const pending=t.status==='pending',rejected=t.status==='rejected',approved=t.status==='approved';const tone=pending?'#fde68a':rejected?'#fca5a5':'#86efac',mark=pending?'⏳ Pending':rejected?'✕ Rejected':approved?'✓ Verified':t.amount<0?'−':'+';return `<div class="ledger"><div><strong style="color:${tone}">${mark}</strong> ${esc(t.label)}<br><small>${esc(t.date)}</small></div><strong style="color:${tone}">${pending||rejected?money(t.displayAmount):t.amount>0?'+':'−'}${pending||rejected?'':money(Math.abs(t.amount))}</strong></div>`}).join('')||'<div class="empty">आपके लेन-देन यहां दिखेंगे।</div>'}</div></div>`}
function detail(){const o=state.orders.find(o=>o.id===active);if(!o)return '';const owner=o.owner===user,participant=mine(o),chat=participant&&o.provider,closed=['completed','cancelled'].includes(o.status);let actions='';
 if(o.status==='open')actions=owner?'<p class="muted">आपकी मांग पोस्ट हो गई है। स्वीकार करने वाले का इंतज़ार है।</p><button class="btn danger" data-action="cancel">मांग रद्द करें</button>':'<button class="btn" data-action="accept">काम स्वीकार करें और बात करें ↗</button>';
 if(chat&&!closed){if(o.proposal){actions+=`<div class="notice">${esc(state.users[o.proposal.by].name)} proposed ${money(o.proposal.items)} for items + ${money(o.proposal.fee)} reward.<br>Total: <strong>${money(o.proposal.items+o.proposal.fee)}</strong></div>`;if(o.proposal.by!==user)actions+='<div class="row"><button class="btn amber" data-action="agree">नई रकम मंज़ूर करें</button><button class="btn secondary" data-action="reject">मंज़ूर नहीं</button></div>';else actions+='<button class="btn secondary small" data-action="withdraw">रकम का सुझाव वापस लें</button>'}
 if(!o.ownerDone&&!o.providerDone)actions+=`<form id="priceForm"><div class="form-grid"><label>सामान की कीमत (₹)<input name="items" type="number" min="0" max="100000" required value="${o.items}"></label><label>डिलीवरी का मेहनताना (₹)<input name="fee" type="number" min="1" max="100000" required value="${o.fee}"></label></div><button class="btn purple small">नई रकम का सुझाव भेजें</button></form>`;
 if(o.status==='chat')actions+=owner?'<p class="muted">काम करने वाले और तय रकम से सहमत हैं?</p><button class="btn" data-action="book" '+(o.proposal?'disabled':'')+'>पुष्टि करके डिलीवरी बुक करें</button><button class="btn secondary small" style="margin:8px" data-action="release">इस व्यक्ति को मना करें</button>':'<p class="muted">मांग पोस्ट करने वाला यहां आपकी बुकिंग की पुष्टि करेगा।</p>';
 if(['booked','delivering'].includes(o.status)){const done=owner?o.ownerDone:o.providerDone;actions+=`<div class="notice">${o.providerDone?'✓ डिलीवरी करने वाले ने पुष्टि कर दी।':'○ डिलीवरी करने वाले की पुष्टि बाकी है।'}<br>${o.ownerDone?'✓ सामान मिलने की पुष्टि हो गई।':'○ सामान मिलने की पुष्टि बाकी है।'}</div>${done?'<p>✓ आपकी पुष्टि हो गई। दूसरे व्यक्ति की पुष्टि का इंतज़ार है।</p>':`<button class="btn ${owner?'':'amber'}" data-action="done" ${o.proposal?'disabled':''}>${owner?'✓ मुझे मेरा सामान मिल गया':'✓ मैंने सामान पहुंचा दिया'}</button>`}`}}
 if(o.status==='completed')actions=`<div class="notice">✓ Both sides confirmed. ${money(total(o))} transferred to ${esc(state.users[o.provider].name)}. Payment settled once.</div>`;
 const stage={open:1,chat:2,booked:3,delivering:3,completed:4,cancelled:0}[o.status];return `<button class="back" data-go="orders">← मेरे ऑर्डर पर वापस जाएं</button><div class="row"><h2>${esc(o.title)}</h2>${badge(o)}</div><div class="detail"><section class="panel"><span class="category-icon">${itemEmoji(o)}</span><h3>मांग की जानकारी</h3><p class="muted">${esc(o.description)}</p><p>⌖ ${esc(o.area)}</p><small>पोस्ट किया: ${esc(state.users[o.owner].name)}</small><div class="progress">${[1,2,3,4].map(i=>`<span class="${i<=stage?'on':''}"></span>`).join('')}</div><div class="ledger"><span>सामान की कीमत</span><strong>${money(o.items)}</strong></div><div class="ledger"><span>डिलीवरी का मेहनताना</span><strong>${money(o.fee)}</strong></div><div class="ledger"><strong>तय कुल रकम</strong><strong>${money(total(o))}</strong></div>${participant?`<p><small>डिलीवरी का पता</small><br>${esc(o.address)}</p>`:'<p class="muted">Exact address shared after you accept.</p>'}<div class="notice">${['booked','delivering'].includes(o.status)?'रकम रिज़र्व है। दोनों की पुष्टि के बाद पैसे ट्रांसफर होंगे।':'Payment status और OTP के लिए नीचे देखें।'}</div></section><section class="panel chat"><div class="chat-head"><strong>${chat?'◉ बातचीत: '+esc(state.users[owner?o.provider:o.owner].name):'मांग की स्थिति'}</strong><br><small>${chat?'सामान और रकम के बारे में यहां बात करें।':'अगला कदम यहां चुनें।'}</small></div>${chat?`<div class="messages" id="messages">${o.messages.map(m=>m.sender==='system'?`<div class="system">${esc(m.text)}</div>`:`<div class="bubble ${m.sender===user?'me':''}">${esc(m.text)}<small>${esc(state.users[m.sender].name)} · ${esc(m.time)}</small></div>`).join('')||'<div class="system">यहां बातचीत शुरू करें।</div>'}</div>${!closed?'<form class="composer" id="chatForm"><input name="message" aria-label="Message" placeholder="अपना संदेश लिखें…" required maxlength="2000" autocomplete="off"><button class="btn" aria-label="संदेश भेजें">➤</button></form>':''}`:''}<div class="actions">${actions||'<p class="muted">यह मांग अभी उपलब्ध नहीं है।</p>'}</div></section></div>`}
function render(){const name=state.users[user].name;document.getElementById('app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="logo">k.</span>KaamSetu<span style="color:#afbf98">.</span></div><div class="caption">YOUR NEIGHBOURHOOD</div><nav class="nav">${[['home','⌂','Discover'],['post','＋','Post request'],['orders','▤','मेरे ऑर्डर'],['messages','◌','Messages'],['wallet','▣','Wallet']].map(([t,i,n])=>`<button data-go="${t}" class="${tab===t?'active':''}"><span>${i}</span>${n}</button>`).join('')}</nav><div class="side-help"><span style="font-size:25px">✳</span><strong>Small tasks. Real connections.</strong><p class="muted">A helping hand for you.<br>A little extra for someone nearby.</p></div></aside><main class="main"><header class="topbar"><span class="mobile-brand">KaamSetu.</span><span class="location">⌖ &nbsp; Siladehi, Chhattisgarh <small> · Your neighbourhood</small></span><div class="profile"><small>Demo user</small><span class="avatar">${name[0]}</span><select id="userSwitch" aria-label="Switch demo user">${Object.entries(state.users).map(([id,u])=>`<option value="${id}" ${user===id?'selected':''}>${esc(u.name)}</option>`).join('')}</select></div></header><div class="content">${active?detail():tab==='home'?home():tab==='post'?postView():tab==='wallet'?walletView():`<div class="row"><h2>${tab==='messages'?'आपकी बातचीत':'मेरे ऑर्डर'}</h2><button class="btn small" data-go="post">＋ नई मांग</button></div><p class="muted">${tab==='messages'?'डिलीवरी से जुड़ी सभी बातचीत यहां देखें।':'आपकी पोस्ट की गई मांगें और स्वीकार किए गए काम।'}</p><div class="grid">${state.orders.filter(o=>mine(o)&&(tab!=='messages'||o.provider)).map(card).join('')||'<div class="empty">अभी कोई ऑर्डर नहीं है। होम पर मांग देखें या अपनी जरूरत पोस्ट करें।</div>'}</div>`}<p class="footnote">रोज़मर्रा की जरूरतों में, आपके आसपास की मदद। &nbsp;·&nbsp; डेमो वेबसाइट — पैसे और बातचीत इसी ब्राउज़र में सेव होते हैं।</p></div></main></div>`;if($('messages'))$('messages').scrollTop=$('messages').scrollHeight}
function transaction(id,amount,label){state.transactions.push({user:id,amount,label,date:new Date().toLocaleString('en-IN')})}
function validMoney(items,fee){return Number.isSafeInteger(items)&&Number.isSafeInteger(fee)&&items>=0&&fee>0&&items<=100000&&fee<=100000}
function act(action){const o=state.orders.find(o=>o.id===active);if(!o)return;const owner=o.owner===user,provider=o.provider===user,participant=owner||provider;
 if(action==='accept'&&o.status==='open'&&!owner){o.provider=user;o.status='chat';system(o,state.users[user].name+' offered to deliver. Please discuss the details; requester confirms the booking.');}
 else if(action==='cancel'&&owner&&o.status==='open'){o.status='cancelled';}
 else if(action==='release'&&owner&&o.status==='chat'){o.provider=null;o.status='open';o.proposal=null;o.messages=[];}
 else if(['agree','reject','withdraw'].includes(action)&&participant&&o.proposal&&!o.ownerDone&&!o.providerDone){const p=o.proposal;if(action==='withdraw'&&p.by!==user)return;if(action!=='withdraw'&&p.by===user)return;if(action==='agree'){const extra=p.items+p.fee-total(o);if(['booked','delivering'].includes(o.status)&&extra>available(o.owner)){toast('बढ़ी हुई रकम मंज़ूर करने के लिए मांग करने वाले को वॉलेट में पैसे जोड़ने होंगे।');return}o.items=p.items;o.fee=p.fee;system(o,'Both agreed to the new total: '+money(total(o))+'.');}else system(o,'Price proposal '+(action==='reject'?'declined':'withdrawn')+'. Previous agreed amount remains.');o.proposal=null;}
 else if(action==='book'&&owner&&o.status==='chat'&&!o.proposal){if(available(user)<total(o)){toast('Insufficient balance. डेमो पैसे जोड़ें in Wallet before booking.');return}o.status='booked';system(o,'Requester confirmed the helper. Already booked — '+money(total(o))+' reserved.');}
 else if(action==='done'&&participant&&['booked','delivering'].includes(o.status)&&!o.proposal){if(owner?o.ownerDone:o.providerDone)return;if(owner)o.ownerDone=true;else o.providerDone=true;o.status='delivering';system(o,owner?'Requester confirmed: मुझे मेरा सामान मिल गया.':'Helper confirmed: मैंने सामान पहुंचा दिया.');if(o.ownerDone&&o.providerDone){const amount=total(o);state.users[o.owner].balance-=amount;state.users[o.provider].balance+=amount;o.status='completed';transaction(o.owner,-amount,o.title);transaction(o.provider,amount,o.title);system(o,'Both confirmed. '+money(amount)+' transferred successfully.');}}
 else return;save();render();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go)go(b.dataset.go);if(b.dataset.open){active=b.dataset.open;render()}if(b.dataset.category){category=b.dataset.category;render()}if(b.dataset.action)act(b.dataset.action)});
document.addEventListener('change',e=>{if(e.target.id==='userSwitch'){user=e.target.value;if(active&&!mine(state.orders.find(o=>o.id===active)))active=null;render()}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;query=e.target.value;render();$('search').focus();$('search').setSelectionRange(pos,pos)}});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target,d=new FormData(f),o=state.orders.find(o=>o.id===active);
 if(f.id==='postForm'){const items=Number(d.get('items')),fee=Number(d.get('fee'));if(!validMoney(items,fee)||!String(d.get('title')).trim()||!String(d.get('description')).trim()||!String(d.get('address')).trim()||!String(d.get('pickup')).trim()){toast('Please enter valid details and whole rupee amounts.');return}state.orders.unshift({id:crypto.randomUUID(),title:d.get('title').trim(),description:d.get('description').trim(),category:d.get('category'),items,fee,area:d.get('pickup').trim(),address:d.get('address').trim(),owner:user,provider:null,status:'open',messages:[],proposal:null,ownerDone:false,providerDone:false});save();go('orders');toast('Your requirement is live!');}
 if(f.id==='topup'){const amount=Number(d.get('amount'));if(!Number.isSafeInteger(amount)||amount<=0||amount>100000)return;state.users[user].balance+=amount;transaction(user,amount,'वॉलेट में डेमो पैसे जोड़े');save();render();toast('डेमो पैसे जुड़ गए।');}
 if(f.id==='chatForm'&&o&&mine(o)&&o.provider&&!['completed','cancelled'].includes(o.status)){const text=d.get('message').trim();if(!text)return;o.messages.push({sender:user,text,time:new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})});save();render();document.querySelector('#chatForm input')?.focus();}
 if(f.id==='priceForm'&&o&&mine(o)&&o.provider&&!o.ownerDone&&!o.providerDone&&!['completed','cancelled'].includes(o.status)){const items=Number(d.get('items')),fee=Number(d.get('fee'));if(!validMoney(items,fee)){toast('सही रकम पूरे रुपये में भरें।');return}if(items===o.items&&fee===o.fee){toast('सुझाव भेजने से पहले रकम बदलें।');return}o.proposal={items,fee,by:user};system(o,state.users[user].name+' proposed a new total of '+money(items+fee)+'. Other person must agree.');save();render();}
});
render();

// Reuse the signed-in Aditya Studio account and its wallet amount. The browser
// keeps the same session keys that the main website already uses.
async function syncStudioWallet(){
  try{
    const raw=localStorage.getItem('aditya_studio_session_v1')||localStorage.getItem('aditya_studio_persistent_login_v2');
    const session=raw?JSON.parse(raw):null;
    if(!session?.sessionToken)return;
    const response=await fetch('/api/restore-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:session.mobile,sessionToken:session.sessionToken})});
    const account=await response.json();
    if(!response.ok||!account?.ok)return;
    user=String(account.id||'me');
    state.users[user]={...(state.users[user]||{}),name:String(account.name||'User'),phone:String(account.mobile||''),balance:Number(account.walletBalance)||0,pendingBalance:Number(account.walletPendingBalance)||0,village:String(account.village||''),address:String(account.address||''),district:String(account.district||''),pincode:String(account.pincode||''),landmark:String(account.landmark||'')};
    state.transactions=(Array.isArray(account.walletHistory)?account.walletHistory:[]).map(t=>({user,amount:t.type==='debit'?-Number(t.amount||0):t.type==='credit'?Number(t.amount||0):0,displayAmount:Number(t.amount||0),status:String(t.type||''),label:t.reason||'Wallet transaction',date:t.timestamp||''}));
    try{const ordersResponse=await fetch('/api/local-delivery/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:session.mobile,sessionToken:session.sessionToken,action:'list'})}),ordersData=await ordersResponse.json();if(ordersResponse.ok&&ordersData.ok)state.orders=Array.isArray(ordersData.orders)?ordersData.orders:state.orders}catch(_){}
    save();render();
  }catch(e){}
}
syncStudioWallet();
window.addEventListener('pageshow',syncStudioWallet);
window.addEventListener('focus',syncStudioWallet);

document.addEventListener('submit',async e=>{
  if(e.target.id!=='redeemCode')return;
  e.preventDefault();
  const raw=localStorage.getItem('aditya_studio_session_v1')||localStorage.getItem('aditya_studio_persistent_login_v2');
  let session=null;try{session=raw?JSON.parse(raw):null}catch(_){}
  if(!session?.sessionToken){toast('पहले Aditya Studio में login करें।');return}
  const code=String(new FormData(e.target).get('code')||'').trim();
  try{
    const response=await fetch('/api/wallet/redeem-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:session.mobile,sessionToken:session.sessionToken,code})});
    const data=await response.json();
    if(!response.ok||!data.ok)throw new Error(data.message||'Code redeem नहीं हुआ।');
    state.users[user].balance=Number(data.walletBalance)||0;
    state.transactions=(data.walletHistory||[]).map(t=>({user,amount:t.type==='debit'?-Number(t.amount||0):t.type==='credit'?Number(t.amount||0):0,displayAmount:Number(t.amount||0),status:String(t.type||''),label:t.reason||'Wallet transaction',date:t.timestamp||''}));
    render();toast(data.message||'Wallet code redeem हो गया।');
  }catch(err){toast(err.message||'Code redeem नहीं हुआ।')}
},true);




