/* Dedicated live chat screen for an accepted Local Delivery order. */
(function(){
 let roomId=null,photo='',photoPreparing=false,lastMessageCount=0,audioReady=false;try{roomId=sessionStorage.getItem('local_delivery_chat_room')||null}catch(_){ }
 const session=()=>{try{return JSON.parse(localStorage.getItem('aditya_studio_session_v1')||localStorage.getItem('aditya_studio_persistent_login_v2')||'null')}catch(_){return null}};
 const mineMessage=m=>m.sender===user;
 function room(){const o=state.orders.find(x=>x.id===roomId);if(!o){roomId=null;return ''}const otherName=o.owner===user?(o.providerName||'Delivery helper'):(o.ownerName||'Customer'),initial=(otherName||'C').trim().charAt(0).toUpperCase(),typing=String(o.typingByMobile||'').replace(/\D/g,'').slice(-10)!==String(session()?.mobile||'').replace(/\D/g,'').slice(-10)&&Date.now()-Number(o.typingAt||0)<5000;return `<main class="chat-room"><header class="chat-room-head"><button class="back" data-close-chat>←</button><div class="chat-avatar">${esc(initial)}</div><div><strong>${esc(otherName)}</strong><small>${typing?'● typing…':'● Live chat'}</small></div><button class="chat-more">⋮</button></header><div class="chat-room-order">📦 ${esc(o.title)} <span>Order chat</span></div><div class="chat-room-messages" id="roomMessages">${(o.messages||[]).map(m=>m.sender==='system'?`<div class="room-system">${esc(m.text)}</div>`:`<div class="room-bubble ${mineMessage(m)?'mine':''}">${m.photo?`<img src="${esc(m.photo)}" alt="Chat photo">`:''}${m.text?`<span>${esc(m.text)}</span>`:''}<small>${esc(m.time||'')} ${mineMessage(m)?((m.seenAt&&m.seenByMobile)?'✓✓ Seen':'✓ Delivered'):''}</small></div>`).join('')}</div><form id="chatRoomForm" class="chat-room-compose"><label class="chat-camera" title="Camera">📷<input id="chatRoomCamera" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" hidden></label><label class="chat-camera" title="Photo upload">🖼️<input id="chatRoomPhoto" type="file" accept="image/jpeg,image/png,image/webp" hidden></label><input name="message" autocomplete="off" maxlength="2000" placeholder="Message लिखें…"><button type="submit">➤</button></form></main>`}
 const viewport=document.querySelector('meta[name=viewport]'),originalViewport=viewport?.getAttribute('content')||'';
 function lockChatZoom(locked){if(!viewport)return;viewport.setAttribute('content',locked?'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no':originalViewport)}
 const before=render;
 render=function(){before();lockChatZoom(!!roomId);try{if(roomId)sessionStorage.setItem('local_delivery_chat_room',roomId);else sessionStorage.removeItem('local_delivery_chat_room')}catch(_){ }if(!roomId)return;const order=state.orders.find(x=>x.id===roomId),count=order?.messages?.length||0,newest=order?.messages?.[count-1];if(lastMessageCount&&count>lastMessageCount&&newest?.sender!==user)chime();lastMessageCount=count;document.getElementById('app').innerHTML=room();const list=document.getElementById('roomMessages');if(list)requestAnimationFrame(()=>list.scrollTop=list.scrollHeight);markSeen()};function chime(){if(!audioReady)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=880;g.gain.setValueAtTime(.001,c.currentTime);g.gain.exponentialRampToValueAtTime(.14,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.22);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.24);setTimeout(()=>c.close(),350)}catch(_){}}
 async function api(action,extra={}){const s=session();if(!s?.sessionToken)throw Error('Login करें');const r=await fetch('/api/local-delivery/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:s.mobile,sessionToken:s.sessionToken,action,orderId:roomId,...extra})}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.message||'Chat update नहीं हुआ');return d}
 async function markSeen(){if(roomId)try{await api('seen')}catch(_){}}
 document.addEventListener('gesturestart',e=>{if(roomId)e.preventDefault()},{passive:false});
 document.addEventListener('gesturechange',e=>{if(roomId)e.preventDefault()},{passive:false});
 document.addEventListener('touchmove',e=>{if(roomId&&e.touches.length>1)e.preventDefault()},{passive:false});
 document.addEventListener('dblclick',e=>{if(roomId&&e.target.closest('.chat-room'))e.preventDefault()},{passive:false});
 document.addEventListener('click',e=>{audioReady=true;const b=e.target.closest('[data-chat-open]');if(b){e.preventDefault();e.stopImmediatePropagation();roomId=b.dataset.chatOpen;lastMessageCount=0;render()}if(e.target.closest('[data-close-chat]')){roomId=null;tab='messages';render()}},true);
 async function prepareChatPhoto(file){if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>12e6)throw Error('JPG, PNG या WEBP photo (12 MB तक) चुनें।');const source=URL.createObjectURL(file);try{const image=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=source});let w=image.naturalWidth||image.width,h=image.naturalHeight||image.height,max=1280;if(Math.max(w,h)>max){const scale=max/Math.max(w,h);w=Math.round(w*scale);h=Math.round(h*scale)}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(image,0,0,w,h);let quality=.82,data=canvas.toDataURL('image/jpeg',quality);while(data.length>1200000&&quality>.45){quality-=.1;data=canvas.toDataURL('image/jpeg',quality)}if(data.length>1200000)throw Error('Photo छोटी चुनें।');return data}finally{URL.revokeObjectURL(source)}}
 document.addEventListener('change',async e=>{if(!['chatRoomPhoto','chatRoomCamera'].includes(e.target.id))return;const file=e.target.files?.[0];photo='';if(!file)return;photoPreparing=true;try{toast('Photo तैयार हो रही है…');photo=await prepareChatPhoto(file);toast('✓ Photo भेजने के लिए तैयार है।')}catch(err){toast(err.message||'Photo तैयार नहीं हुई।');e.target.value=''}finally{photoPreparing=false}});
 let typingTimer;
 document.addEventListener('input',e=>{if(e.target.closest('#chatRoomForm input[name=message]')){clearTimeout(typingTimer);typingTimer=setTimeout(()=>api('typing').catch(()=>{}),150)}});
 document.addEventListener('submit',async e=>{if(e.target.id!=='chatRoomForm')return;e.preventDefault();e.stopImmediatePropagation();const text=String(new FormData(e.target).get('message')||'').trim();if(photoPreparing){toast('Photo तैयार होने का इंतज़ार करें।');return}if(!text&&!photo)return;const button=e.target.querySelector('button[type=submit]');button.disabled=true;try{await api('message',{text,photo});photo='';chime();await syncStudioWallet()}catch(err){toast(err.message||'Message नहीं गया')}finally{button.disabled=false}},true);
if(roomId)render();})();
