let known=new Set(),member='',alertsOn=localStorage.getItem('deliverybro_alerts')!=='off',nativePushReady=false,nativeToken='',alertTimer=null;const $=id=>document.getElementById(id);function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nativePush(){return window.Capacitor?.Plugins?.PushNotifications||null}
async function savePushToken(token){nativeToken=token||nativeToken;if(!nativeToken)return;try{await fetch('/api/orderbro/push-token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:nativeToken,enabled:alertsOn})})}catch(_){}}
function hideOrderAlert(){clearTimeout(alertTimer);$('popup').hidden=true}
function showOrderAlert(data={},fallback={}){if(!alertsOn)return;const title=data.title||fallback.title||'नया food order आया है',pickup=data.pickup||data.shopName||'Food shop',drop=data.drop||data.address||'—',earning=Number(data.earning??data.fee??0),price=Number(data.items??data.price??0);$('popTitle').textContent=title;$('popItem').textContent=title.replace(/^New delivery:\s*/i,'');$('popPrice').textContent='₹'+price;$('popEarning').textContent='₹'+earning;$('popPickup').textContent=pickup;$('popDrop').textContent=drop;$('popup').hidden=false;const bar=$('popupProgress');bar.style.animation='none';void bar.offsetWidth;bar.style.animation='alertFill 30s linear forwards';clearTimeout(alertTimer);alertTimer=setTimeout(hideOrderAlert,30000);navigator.vibrate&&navigator.vibrate([250,100,250])}
async function requestNativePermission(){const push=nativePush();if(!push)return 'unavailable';try{let permission=await push.checkPermissions();if(permission.receive==='prompt')permission=await push.requestPermissions();return permission.receive||'denied'}catch(_){return 'unavailable'}}
async function enableNativeAlerts(){const push=nativePush();if(!push||nativePushReady)return;try{const state=await requestNativePermission();if(state!=='granted')return;push.addListener('registration',t=>savePushToken(t.value));push.addListener('registrationError',()=>{});push.addListener('pushNotificationReceived',n=>showOrderAlert(n.data||{},n));push.addListener('pushNotificationActionPerformed',()=>{location.href='/deliverybro'});await push.createChannel?.({id:'delivery_orders',name:'Food delivery alerts',description:'New food orders',importance:5,visibility:1,sound:'default',vibration:true});await push.register();nativePushReady=true}catch(_){}}
async function login(){ $('err').textContent='';let r=await fetch('/api/orderbro/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('user').value,password:$('pass').value,role:'delivery'})}),d=await r.json();if(!r.ok){$('err').textContent=d.message||'Login नहीं हुआ';return}member=d.displayName||d.shopName||'Delivery boy';$('login').hidden=true;$('panel').hidden=false;$('logout').hidden=false;await enableNativeAlerts();load(true)}
function setupAlerts(){const sw=$('alertSwitch'),menu=$('alertMenu'),more=$('more');if(!sw||sw.dataset.ready)return;sw.checked=alertsOn;sw.onchange=()=>{alertsOn=sw.checked;localStorage.setItem('deliverybro_alerts',alertsOn?'on':'off');savePushToken('')};more.onclick=e=>{e.stopPropagation();menu.hidden=!menu.hidden};menu.onclick=e=>e.stopPropagation();document.addEventListener('click',()=>menu.hidden=true);sw.dataset.ready='1'}
function card(o){const mine=String(o.deliveryAcceptedById||'');const accepted=!!mine;return `<article class="card order ${accepted?'accepted':''}"><div class="top"><div><h2 style="margin:0 0 5px">${esc(o.title)}</h2><small>🏪 ${esc(o.shopName||'Food shop')} · ${new Date(o.createdAt).toLocaleString('en-IN')}</small></div><span class="tag ${accepted?'ok':''}">${accepted?'ASSIGNED':'OPEN'}</span></div><div class="details"><div><b>Pickup shop</b>${esc(o.shopName||'—')}</div><div><b>Customer</b>${esc(o.ownerName||'—')}<br>${esc(o.ownerMobile||'—')}</div><div><b>Drop address</b>${esc(o.address||'—')}<br>${esc(o.deliveryVillage||o.area||'—')}</div><div><b>Delivery earning</b>₹${Number(o.fee||0)}</div></div>${accepted?`<p class="sub">Delivery: ${esc(o.providerName||'—')} ${o.providerMobile?'· '+esc(o.providerMobile):''}</p>`:`<button onclick="acceptOrder('${esc(o.id)}')">🚚 यह delivery accept करें</button>`}</article>`}
async function acceptOrder(id){let r=await fetch('/api/orderbro/accept',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:id})}),d=await r.json();if(!r.ok)return alert(d.message||'Accept नहीं हुआ');load(false)}
async function load(first){setupAlerts();let r=await fetch('/api/orderbro/orders'),d=await r.json();if(r.status===401){$('login').hidden=false;$('panel').hidden=true;return}if(!r.ok)return;let rows=d.orders||[];if(!first){let fresh=rows.find(o=>!known.has(o.id)&&!o.deliveryAcceptedById);if(fresh)showOrderAlert({title:'New delivery: '+fresh.title,pickup:fresh.shopName||'Food shop',drop:fresh.address||fresh.deliveryVillage||fresh.area||'—',price:fresh.items||0,earning:fresh.fee||0})}known=new Set(rows.map(o=>o.id));$('orders').innerHTML=rows.length?rows.sort((a,b)=>Number(!!a.deliveryAcceptedById)-Number(!!b.deliveryAcceptedById)).map(card).join(''):'<div class="card empty">अभी कोई food delivery open नहीं है।</div>'}
$('signin').onclick=login;$('pass').onkeydown=e=>{if(e.key==='Enter')login()};$('logout').onclick=async()=>{await fetch('/api/orderbro/logout',{method:'POST'});location.reload()};load(true);setInterval(()=>load(false),5000);
// Food orders clearly show whether they are a scheduled pre-book or an immediate order.
(() => {
  const baseCard=card;
  card=o=>{
    const pre=String(o.foodOrderType||'')==='pre-book'||(!o.foodOrderType&&new Date(o.neededBy||0).toDateString()!==new Date(o.createdAt||0).toDateString());
    const label=pre?'📅 PRE-BOOK · scheduled time':'⚡ ORDER NOW · immediate';
    const color=pre?'background:#064e3b;border:1px solid #34d399;color:#d1fae5':'background:#522006;border:1px solid #fbbf24;color:#fef3c7';
    return baseCard(o).replace('<div class="details">','<div style="'+color+';padding:9px;border-radius:9px;margin:12px 0;font-weight:800;font-size:13px">'+label+'</div><div class="details">');
  };
})();
