labels.disputed='शिकायत · रकम hold';
function commitDelivery(action,data){const draft=JSON.parse(JSON.stringify(state));try{const result=DeliveryEngine.run(draft,active,user,action,data);localStorage.setItem(KEY,JSON.stringify(draft));state=draft;render();if(result.error)toast(result.message);return result}catch(e){toast(e.message||'बदलाव सेव नहीं हुए।');return null}}
act=function(action){return commitDelivery(action,{})};
const deliveryDetailBefore=detail;
detail=function(){const html=deliveryDetailBefore();const o=state.orders.find(o=>o.id===active);if(!o)return html;if(!mine(o)){return html+'<div class="notice">Accept करने पर आपके wallet में सामान की कीमत जितना deposit lock होगा: '+money(o.items)+'. उपलब्ध balance: '+money(available(user))+'. Customer की रकम '+money(total(o))+' भी साथ lock होगी।</div>'}const owner=o.owner===user;let panel=`<section class="delivery-security"><h3>▣ Payment & deposit lock</h3><div class="lock-grid"><div><small>Customer की रकम</small><strong>${money(o.customerHold??(['booked','delivering'].includes(o.status)?total(o):0))}</strong></div><div><small>Helper का deposit</small><strong>${money(o.helperHold||0)}</strong></div></div><p class="muted">Customer: सामान + delivery charge। Helper: सामान की कीमत जितना deposit। यह local demo है।</p>`;
 if(o.status==='chat')panel+=`<p>दोनों balances reserve हैं। Helper को खरीदारी के लिए अलग पैसे चाहिए।</p>${!owner?'<button class="btn secondary" data-action="leave">Booking से पहले काम छोड़ें</button>':''}`;
 if(o.proposal){const change=(o.proposal.items+o.proposal.fee)-total(o),amount=o.proposal.items+o.proposal.fee;let proposalNote=change===0?'नई रकम वही है।':change>0?`नई रकम ${money(change)} ज्यादा है। Customer की मंज़ूरी के बाद ही यह रकम lock होगी।`:`नई रकम ${money(Math.abs(change))} कम है। Customer की मंज़ूरी के बाद इतनी रकम wallet में वापस unlock होगी।`;if(owner&&o.proposal.by!==user&&change>0){const shortage=Math.max(0,amount-(DeliveryEngine.available(state,user)+(Number(o.customerHold)||0)));if(shortage)proposalNote+=` Wallet में ${money(shortage)} कम है। मंज़ूर करने से पहले पैसे जोड़ें। <button type="button" class="btn small" data-go="wallet">＋ पैसा ऐड करें</button>`}panel+=`<div class="notice"><strong>रकम बदलने का प्रस्ताव</strong><br>नया total: ${money(amount)}<br>${proposalNote}</div>`;}
 if(['booked','delivering'].includes(o.status)&&!o.cancelBy){
  if(owner){panel+=`<p class="notice">पहले सामान और quantity check करें। सामान मिलने से पहले OTP किसी को न दें।</p><button class="btn" data-action="otp" ${o.proposal?'disabled':''}>${o.otp?'नया OTP बनाएं':'✓ सामान मिल गया — OTP दिखाएं'}</button>`;if(o.otp)panel+=`<div class="otp-box"><small>आपका delivery OTP</small><strong>${esc(o.otp.code)}</strong><span>Valid till ${new Date(o.otp.expiresAt).toLocaleTimeString('en-IN')} · 10 मिनट</span></div>`}
  else panel+=`<form id="deliveryOtpForm"><label>Customer का delivery OTP<input name="otp" required pattern="[0-9]{6}" minlength="6" maxlength="6" inputmode="numeric" autocomplete="one-time-code" placeholder="6 digit OTP"></label><button class="btn amber" ${!o.otp?'disabled':''}>OTP verify करें — सामान दे दिया</button></form><small>${o.otp?'Customer से सामान देने के बाद OTP लें।':'Customer पहले सामान check करके OTP बनाएगा।'}</small>`;
 }
 if(['booked','delivering','disputed'].includes(o.status)){
  if(o.status==='disputed')panel+=`<div class="notice">शिकायत: ${esc(o.dispute?.reason)}<br>Payment frozen है। इस demo में admin arbitration नहीं है; दोनों की सहमति के बिना रकम release नहीं होगी।</div>`;
  else panel+='<details><summary>समस्या / शिकायत करें</summary><form id="deliveryDisputeForm"><label>क्या समस्या है?<textarea name="reason" required maxlength="1000" placeholder="सामान नहीं मिला, गलत सामान या अन्य समस्या"></textarea></label><button class="btn danger">शिकायत करें — payment रोकें</button></form></details>';
  panel+=o.cancelBy?(o.cancelBy===user?'<p class="notice">Cancellation के लिए दूसरे user की सहमति बाकी है।</p>':'<div class="notice">दूसरा user बिना payment cancel करना चाहता है। सामान और खर्च का हिसाब पहले तय करें।</div><button class="btn danger" data-action="cancel-request">सहमत हूँ — cancel और unlock करें</button><button class="btn secondary" data-action="cancel-reject">मंज़ूर नहीं</button>'):'<button class="btn secondary" data-action="cancel-request">दोनों की सहमति से cancel का अनुरोध</button>';
 }
 if(o.status==='completed')panel+='<div class="notice">✓ OTP verified। Payment settle हो गया और helper का deposit unlock हो गया।</div>';
 panel+='</section>';return html+panel;
};
const deliveryRenderBefore=render;
render=function(){deliveryRenderBefore();if(demoLoggedOut)return;document.querySelectorAll('[data-action="done"]').forEach(b=>b.remove());const o=state.orders.find(o=>o.id===active);if(o&&(o.status==='disputed'||o.cancelBy)){document.getElementById('priceForm')?.remove();document.querySelectorAll('[data-edit-order]').forEach(b=>b.remove())}const content=document.querySelector('.content');if(content){const box=document.createElement('div');box.className='demo-role-switch';box.innerHTML=`<label>Flow test करें — demo user<select id="deliveryDemoUser">${Object.entries(state.users).map(([id,u])=>`<option value="${id}" ${id===user?'selected':''}>${esc(u.name)}</option>`).join('')}</select></label><small>सिर्फ local demo: role बदलकर दोनों तरफ का flow देखें। OTP असली सुरक्षा के लिए server पर बनेगा।</small>`;content.append(box)}};
document.addEventListener('change',e=>{if(e.target.id==='deliveryDemoUser'){user=e.target.value;editingOrderId=null;render()}});
document.addEventListener('submit',e=>{if(!['priceForm','deliveryOtpForm','deliveryDisputeForm'].includes(e.target.id))return;e.preventDefault();e.stopImmediatePropagation();const d=new FormData(e.target);if(e.target.id==='priceForm')commitDelivery('propose',{items:Number(d.get('items')),fee:Number(d.get('fee'))});if(e.target.id==='deliveryOtpForm')commitDelivery('verify',{code:String(d.get('otp')).trim()});if(e.target.id==='deliveryDisputeForm')commitDelivery('dispute',{reason:d.get('reason')})},true);
render();

