labels.disputed='शिकायत · रकम hold';
function commitDelivery(action,data){const draft=JSON.parse(JSON.stringify(state));try{const result=DeliveryEngine.run(draft,active,user,action,data);localStorage.setItem(KEY,JSON.stringify(draft));state=draft;render();if(result.error)toast(result.message);return result}catch(e){toast(e.message||'बदलाव सेव नहीं हुए।');return null}}
act=async function(action){const order=state.orders.find(o=>o.id===active);const raw=localStorage.getItem('aditya_studio_session_v1')||localStorage.getItem('aditya_studio_persistent_login_v2');let session=null;try{session=raw?JSON.parse(raw):null}catch(_){}if(action==='accept'&&order?.status==='open'){try{const res=await fetch('/api/local-delivery/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:session?.mobile,sessionToken:session?.sessionToken,action:'accept',orderId:order.id})}),data=await res.json();if(!res.ok||!data.ok){toast(data.message||'Order accept नहीं हुआ');return null}order.provider=user;order.status='chat';order.providerMobile=session.mobile;order.providerName=data.order?.providerName||state.users[user]?.name||'Delivery helper';system(order,'काम स्वीकार हुआ। अब customer से details पर बात करें।');save();render();toast('✓ Order accept हो गया। Customer को alert भेज दिया गया।');return data}catch(_){toast('Order accept करने के लिए internet check करें।');return null}}if(action==='cancel'&&order?.status==='open'){try{if(!session?.sessionToken)throw new Error('Login required');const res=await fetch('/api/local-delivery/unlock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:session.mobile,sessionToken:session.sessionToken,orderId:order.id})}),data=await res.json();if(!res.ok||!data.ok)throw new Error(data.message||'Refund नहीं हुआ');state.users[user].balance=Number(data.walletBalance||0);toast('₹'+data.refunded+' wallet में वापस आ गए।')}catch(e){toast('Order cancel हो रहा है। पुराने order का server lock record नहीं मिला।')}}return commitDelivery(action,{})};
// A home-card accept button carries both data-open and data-action. Handle it
// before the generic click handler so rendering cannot interrupt its request.
document.addEventListener('click',e=>{const b=e.target.closest('button[data-open][data-action="accept"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();active=b.dataset.open;act('accept')},true);
const deliveryDetailBefore=detail;
detail=function(){const html=deliveryDetailBefore();const o=state.orders.find(o=>o.id===active);if(!o)return html;if(!mine(o)){return html+'<div class="notice">Accept Order करने के लिए आपके wallet में पैसा होना जरूरी नहीं है। Customer की रकम पहले से lock है; helper सामान अपने पैसे से लाएगा और delivery के बाद payment पाएगा।</div>'}const owner=o.owner===user;let panel=`<section class="delivery-security"><h3>▣ Payment & deposit lock</h3><div class="lock-grid"><div><small>Customer की रकम</small><strong>${money(o.customerHold??(['booked','delivering'].includes(o.status)?total(o):0))}</strong></div><div><small>Helper का lock</small><strong>${money(o.helperHold||0)}</strong></div></div><p class="muted">Customer: सामान + delivery charge। Helper: अपना पैसा लगाकर सामान लाएगा। यह local demo है।</p>`;
 if(o.status==='chat')panel+=`<p>दोनों balances reserve हैं। Helper को खरीदारी के लिए अलग पैसे चाहिए।</p>${!owner?'<button class="btn secondary" data-action="leave">Booking से पहले काम छोड़ें</button>':''}`;
 if(o.proposal){const change=(o.proposal.items+o.proposal.fee)-total(o),amount=o.proposal.items+o.proposal.fee;let proposalNote=change===0?'नई रकम वही है।':change>0?`नई रकम ${money(change)} ज्यादा है। Customer की मंज़ूरी के बाद ही यह रकम lock होगी।`:`नई रकम ${money(Math.abs(change))} कम है। Customer की मंज़ूरी के बाद इतनी रकम wallet में वापस unlock होगी।`;if(owner&&o.proposal.by!==user&&change>0){const shortage=Math.max(0,amount-(DeliveryEngine.available(state,user)+(Number(o.customerHold)||0)));if(shortage)proposalNote+=` Wallet में ${money(shortage)} कम है। मंज़ूर करने से पहले पैसे जोड़ें। <button type="button" class="btn small" data-go="wallet">＋ पैसा ऐड करें</button>`}panel+=`<div class="notice"><strong>रकम बदलने का प्रस्ताव</strong><br>नया total: ${money(amount)}<br>${proposalNote}</div>`;}
 if(['booked','delivering'].includes(o.status)&&!o.cancelBy){
  if(owner){panel+=`<p class="notice">पहले सामान और quantity check करें। सामान मिलने से पहले OTP किसी को न दें।</p><button class="btn" data-action="otp" ${o.proposal?'disabled':''}>${o.otp?'नया OTP बनाएं':'✓ सामान मिल गया — OTP दिखाएं'}</button>`;if(o.otp)panel+=`<div class="otp-box"><small>आपका delivery OTP</small><strong>${esc(o.otp.code)}</strong><span>Valid till ${new Date(o.otp.expiresAt).toLocaleTimeString('en-IN')} · 10 मिनट</span></div>`}
  else panel+=`<form id="deliveryOtpForm"><label>Customer का delivery OTP<input name="otp" required pattern="[0-9]{6}" minlength="6" maxlength="6" inputmode="numeric" autocomplete="one-time-code" placeholder="6 digit OTP"></label><button class="btn amber" ${!o.otp?'disabled':''}>OTP verify करें — सामान दे दिया</button></form><small>${o.otp?'Customer से सामान देने के बाद OTP लें।':'Customer पहले सामान check करके OTP बनाएगा।'}</small>`;
 }
 if(['booked','delivering','disputed'].includes(o.status)){
  if(o.status==='disputed')panel+=`<div class="notice">शिकायत: ${esc(o.dispute?.reason)}<br>Payment frozen है। इस demo में admin arbitration नहीं है; दोनों की सहमति के बिना रकम release नहीं होगी।</div>`;
  else panel+='<details><summary>समस्या / शिकायत करें</summary><form id="deliveryDisputeForm"><label>क्या समस्या है?<textarea name="reason" required maxlength="1000" placeholder="सामान नहीं मिला, गलत सामान या अन्य समस्या"></textarea></label><button class="btn danger">शिकायत करें — payment रोकें</button></form></details>';
  panel+=o.cancelBy?(o.cancelBy===user?'<p class="notice">Cancellation के लिए दूसरे user की सहमति बाकी है।</p>':'<div class="notice">दूसरा user बिना payment cancel करना चाहता है। सामान और खर्च का हिसाब पहले तय करें।</div><button class="btn danger" data-action="cancel-request">सहमत हूँ — cancel और unlock करें</button><button class="btn secondary" data-action="cancel-reject">मंज़ूर नहीं</button>'):'<button class="btn secondary" data-action="cancel-request">दोनों की सहमति से cancel का अनुरोध</button>';
 }
 if(o.status==='completed')panel+='<div class="notice">✓ OTP verified। Payment settle हो गया और helper का deposit unlock हो गया।</div>';
 panel+='</section>';return html+panel;
};
const deliveryRenderBefore=render;
render=function(){deliveryRenderBefore();if(demoLoggedOut)return;document.querySelectorAll('[data-action="done"]').forEach(b=>b.remove());const o=state.orders.find(o=>o.id===active);if(o&&(o.status==='disputed'||o.cancelBy)){document.getElementById('priceForm')?.remove();document.querySelectorAll('[data-edit-order]').forEach(b=>b.remove())}};
document.addEventListener('submit',e=>{if(!['priceForm','deliveryOtpForm','deliveryDisputeForm'].includes(e.target.id))return;e.preventDefault();e.stopImmediatePropagation();const d=new FormData(e.target);if(e.target.id==='priceForm')commitDelivery('propose',{items:Number(d.get('items')),fee:Number(d.get('fee'))});if(e.target.id==='deliveryOtpForm')commitDelivery('verify',{code:String(d.get('otp')).trim()});if(e.target.id==='deliveryDisputeForm')commitDelivery('dispute',{reason:d.get('reason')})},true);
render();

