labels.disputed='शिकायत · रकम hold';
function commitDelivery(action,data){const draft=JSON.parse(JSON.stringify(state));try{const result=DeliveryEngine.run(draft,active,user,action,data);localStorage.setItem(KEY,JSON.stringify(draft));state=draft;render();if(result.error)toast(result.message);return result}catch(e){toast(e.message||'बदलाव सेव नहीं हुए।');return null}}
act=async function(action){const order=state.orders.find(o=>o.id===active);const raw=localStorage.getItem('aditya_studio_session_v1')||localStorage.getItem('aditya_studio_persistent_login_v2');let session=null;try{session=raw?JSON.parse(raw):null}catch(_){}if(action==='accept'&&['open','chat'].includes(order?.status)){try{const res=await fetch('/api/local-delivery/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:session?.mobile,sessionToken:session?.sessionToken,action:'accept',orderId:order.id})}),data=await res.json();if(!res.ok||!data.ok){toast(data.message||'Order accept नहीं हुआ');return null}order.provider=user;order.status='chat';order.providerMobile=session.mobile;order.providerName=data.order?.providerName||state.users[user]?.name||'Delivery helper';system(order,'काम स्वीकार हुआ। अब customer से details पर बात करें।');save();render();toast('✓ Order accept हो गया। Customer को alert भेज दिया गया।');return data}catch(_){toast('Order accept करने के लिए internet check करें।');return null}}if(action==='cancel'&&order?.status==='open'){try{if(!session?.sessionToken)throw new Error('Login required');const res=await fetch('/api/local-delivery/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:session.mobile,sessionToken:session.sessionToken,action:'owner-delete',orderId:order.id})}),data=await res.json();if(!res.ok||!data.ok)throw new Error(data.message||'Order cancel नहीं हुआ');state.users[user].balance=Number(data.walletBalance||state.users[user].balance||0);toast('Order cancel हो गया। Locked पैसे wallet में वापस आ गए।')}catch(e){toast(e.message||'Order cancel नहीं हुआ');return null}}return commitDelivery(action,{})};
// A home-card accept button carries both data-open and data-action. Handle it
// before the generic click handler so rendering cannot interrupt its request.
document.addEventListener('click',e=>{const b=e.target.closest('button[data-open][data-action="accept"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();active=b.dataset.open;act('accept')},true);
document.addEventListener('submit',async e=>{if(e.target.id!=='chatForm')return;e.preventDefault();e.stopImmediatePropagation();const f=e.target,order=state.orders.find(o=>o.id===active),text=String(new FormData(f).get('message')||'').trim();if(!order||!text)return;let session=null;try{session=JSON.parse(localStorage.getItem('aditya_studio_session_v1')||localStorage.getItem('aditya_studio_persistent_login_v2')||'null')}catch(_){}if(!session?.sessionToken){toast('पहले login करें।');return}const button=f.querySelector('button');if(button)button.disabled=true;try{const res=await fetch('/api/local-delivery/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:session.mobile,sessionToken:session.sessionToken,action:'message',orderId:order.id,text})}),data=await res.json();if(!res.ok||!data.ok)throw new Error(data.message||'Message नहीं गया');order.messages=Array.isArray(order.messages)?order.messages:[];order.messages.push({sender:user,text,time:data.message?.time||new Date().toLocaleTimeString('en-IN')});save();render();toast('✓ Message भेज दिया गया।')}catch(err){toast(err.message||'Message नहीं भेजा गया।')}finally{if(button)button.disabled=false}},true);
const deliveryDetailBefore=detail;
detail=function(){const html=deliveryDetailBefore();const o=state.orders.find(o=>o.id===active);if(!o)return html;
 if(o.status==='chat'&&o.provider===user&&o.owner!==user){const items=Array.isArray(o.lineItems)&&o.lineItems.length?o.lineItems:[{name:o.title||'सामान',quantity:o.quantity||''}],instructions=String(o.description||'').split('\n').filter(x=>!x.startsWith('मात्रा:')&&!x.startsWith('कब तक चाहिए:')).join('\n').trim();return '<section class="accepted-order-page"><button class="track-back" data-go="home">← आसपास की जरूरतों पर वापस जाएं</button><span class="accepted-eyebrow">✓ DELIVERY REQUEST ACCEPTED</span><h1>'+esc(o.title)+'</h1><section class="accepted-order-card"><h2>📋 Requirement details</h2><div class="accepted-person"><span>'+esc((o.ownerName||'C').charAt(0).toUpperCase())+'</span><div><small>Order करने वाले user</small><strong>'+esc(o.ownerName||'Customer')+'</strong></div></div><div class="accepted-route"><div><small>📍 Pickup · कहां से लेना है</small><strong>'+esc(o.area||'जगह नहीं बताई')+'</strong></div><b>→</b><div><small>🏠 Drop-off · कहां पहुंचाना है</small><strong>'+esc(o.deliveryVillage||o.address||'पता chat में confirm करें')+'</strong></div></div><div class="accepted-items"><h3>🛍️ सामान की सूची</h3>'+items.map((x,i)=>'<div><b>'+String(i+1).padStart(2,'0')+'</b><span>'+esc(x.name||'सामान')+'</span><strong>'+esc(x.quantity||'Quantity नहीं बताई')+'</strong></div>').join('')+'</div><div class="accepted-notes"><strong>📝 ज़रूरी बातें</strong><p>'+esc(instructions||'कोई अतिरिक्त निर्देश नहीं दिए गए हैं।')+'</p></div></section><section class="accepted-confirm"><strong>Pickup order अभी confirm नहीं हुआ है</strong><p>Order करने वाले user से chat में बात करके दुकान, सामान और delivery details confirm करें। Customer confirmation के बाद ही delivery final होगी।</p><button class="btn accepted-chat-button" data-chat-open="'+esc(o.id)+'">💬 Order करने वाले से बात करें</button></section></section>'}if(!mine(o)){return html+'<div class="notice">Accept Order करने के लिए आपके wallet में पैसा होना जरूरी नहीं है। Customer की रकम पहले से lock है; helper सामान अपने पैसे से लाएगा और delivery के बाद payment पाएगा।</div>'}const owner=o.owner===user;let panel=`<section class="delivery-security"><h3>▣ Payment & deposit lock</h3><div class="lock-grid"><div><small>Customer की रकम</small><strong>${money(o.customerHold??(['booked','delivering'].includes(o.status)?total(o):0))}</strong></div><div><small>Helper का lock</small><strong>${money(o.helperHold||0)}</strong></div></div><p class="muted">Customer: सामान + delivery charge। Helper: अपना पैसा लगाकर सामान लाएगा। यह local demo है।</p>`;
 if(o.status==='chat')panel+=`<p>दोनों balances reserve हैं। Helper को खरीदारी के लिए अलग पैसे चाहिए।</p>${!owner?'<button class="btn secondary" data-action="leave">Booking से पहले काम छोड़ें</button>':''}`;
 if(o.proposal){const change=(o.proposal.items+o.proposal.fee)-total(o),amount=o.proposal.items+o.proposal.fee;let proposalNote=change===0?'नई रकम वही है।':change>0?`नई रकम ${money(change)} ज्यादा है। Customer की मंज़ूरी के बाद ही यह रकम lock होगी।`:`नई रकम ${money(Math.abs(change))} कम है। Customer की मंज़ूरी के बाद इतनी रकम wallet में वापस unlock होगी।`;if(owner&&o.proposal.by!==user&&change>0){const shortage=Math.max(0,amount-(DeliveryEngine.available(state,user)+(Number(o.customerHold)||0)));if(shortage)proposalNote+=` Wallet में ${money(shortage)} कम है। मंज़ूर करने से पहले पैसे जोड़ें। <button type="button" class="btn small" data-go="wallet">＋ पैसा ऐड करें</button>`}panel+=`<div class="notice"><strong>रकम बदलने का प्रस्ताव</strong><br>नया total: ${money(amount)}<br>${proposalNote}</div>`;}
 if(['booked','delivering'].includes(o.status)&&!o.cancelBy){
  if(owner){panel+=`<p class="notice">पहले सामान और quantity check करें। सामान मिलने से पहले OTP किसी को न दें।</p>`;if(!o.otp)panel+=`<button class="btn" data-action="otp" ${o.proposal?'disabled':''}>✓ सामान मिल गया — OTP दिखाएं</button>`;else panel+=`<div class="otp-box"><small>आपका delivery OTP · Delivery boy verify करने तक दिखेगा</small><strong>${esc(o.otp.code)}</strong></div>`}
  else panel+=`<form id="deliveryOtpForm"><label>Customer का delivery OTP<input name="otp" required pattern="[0-9]{6}" minlength="6" maxlength="6" inputmode="numeric" autocomplete="one-time-code" placeholder="6 digit OTP"></label><button class="btn amber" ${!o.otp?'disabled':''}>OTP verify करें — सामान दे दिया</button></form><small>${o.otp?'Customer से सामान देने के बाद OTP लें।':'Customer पहले सामान check करके OTP बनाएगा।'}</small>`;
 }
 if(['booked','delivering','disputed'].includes(o.status)){
  panel+='<div class="notice delivery-final-lock">🔒 दोनों तरफ से delivery final confirm हो चुकी है। अब यह order cancel या किसी दूसरे delivery boy को transfer नहीं हो सकता। सहायता चाहिए तो नीचे Help चुनें।</div><a class="btn secondary" href="https://wa.me/?text=Local%20Delivery%20help%20required%20for%20order%20'+encodeURIComponent(o.id)+'" target="_blank" rel="noopener">⚠️ Help / WhatsApp support</a>';
 }
 if(o.status==='completed')panel+='<div class="notice">✓ OTP verified। Payment settle हो गया और helper का deposit unlock हो गया।</div>';
 panel+='</section>';return html+panel;
};
const deliveryRenderBefore=render;
render=function(){deliveryRenderBefore();document.querySelectorAll('[data-action="done"]').forEach(b=>b.remove());const o=state.orders.find(o=>o.id===active);if(o&&mine(o)&&['chat','booked','delivering'].includes(o.status)){const panel=document.querySelector('.detail .chat');if(panel){const owner=o.owner===user,label=owner?'💬 Delivery boy से बात करें':'💬 Order करने वाले से बात करें';const candidates=Array.isArray(o.candidateSessions)?o.candidateSessions:[];const choices=owner&&o.status==='chat'?'<div class="chat-head"><strong>💬 Delivery boy चुनकर बातचीत करें</strong><br><small>हर delivery boy का chat, quote और confirmation अलग रहेगा।</small></div><div class="candidate-chat-list">'+(candidates.length?candidates.map(c=>'<button class="btn" data-chat-open="'+esc(o.id)+'" data-chat-peer="'+esc(c.mobile||'')+'">💬 '+esc(c.name||'Delivery boy')+' से बात करें →</button>').join(''):'<small>अभी किसी delivery boy ने बात शुरू नहीं की है।</small>')+'</div>':'<div class="chat-head"><strong>'+label+'</strong><br><small>सारी बातचीत अलग live chat page में होगी।</small></div><button class="btn" data-chat-open="'+esc(o.id)+'" style="margin-top:12px">'+label+' →</button>';panel.innerHTML=choices}}if(o&&(o.status==='disputed'||o.cancelBy)){document.getElementById('priceForm')?.remove();document.querySelectorAll('[data-edit-order]').forEach(b=>b.remove())}};
document.addEventListener('submit',e=>{if(!['priceForm','deliveryOtpForm','deliveryDisputeForm'].includes(e.target.id))return;e.preventDefault();e.stopImmediatePropagation();const d=new FormData(e.target);if(e.target.id==='priceForm')commitDelivery('propose',{items:Number(d.get('items')),fee:Number(d.get('fee'))});if(e.target.id==='deliveryOtpForm')commitDelivery('verify',{code:String(d.get('otp')).trim()});if(e.target.id==='deliveryDisputeForm')commitDelivery('dispute',{reason:d.get('reason')})},true);
render();

// local-delivery.html historically includes legacy Receive overrides after this
// script. Run once after parsing so Delivery Receive always opens the proven
// request-detail, accept, and chat flow instead of routing to Orders.
setTimeout(() => {
  const renderBeforeReceiveRestore = render;
  const safeText = value => String(value == null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  const formatMoney = value => '₹' + Math.max(0, Number(value) || 0).toLocaleString('en-IN');
  const requestCard = order => {
    const owner = state.users[order.owner] || {};
    const itemList = Array.isArray(order.lineItems) && order.lineItems.length
      ? order.lineItems.map(item => `<li><strong>${safeText(item.name || 'सामान')}</strong>${item.quantity ? ` · ${safeText(item.quantity)}` : ''}</li>`).join('')
      : `<li><strong>${safeText(order.title || 'सामान')}</strong>${order.quantity ? ` · ${safeText(order.quantity)}` : ''}</li>`;
    return `<article class="card receive-full-card"><div class="row"><span class="badge">खुली मांग</span><div class="reward"><small>DELIVERY REWARD</small><strong>${formatMoney(order.fee)}</strong></div></div><div class="request-heading"><span class="category-icon">🛍️</span><div><small>${safeText(order.category || 'सामान')}</small><h3>${safeText(order.title || 'Delivery request')}</h3></div></div><p class="description">${safeText(order.description || 'कोई अतिरिक्त जानकारी नहीं दी गई है।')}</p><section class="receive-items"><small>सामान और Quantity</small><ul>${itemList}</ul></section><div class="route"><div><span class="route-dot"></span><div><small>PICKUP / ROUTE</small><p>${safeText(order.area || 'Pickup location')}</p></div></div><div><span class="route-dot destination"></span><div><small>DROP-OFF</small><p>${safeText(order.deliveryVillage || order.address || 'Delivery location')}</p></div></div></div><div class="row card-footer"><small>${safeText(owner.name || 'Customer')}<br>Items estimate: ${formatMoney(order.items)}</small><button class="btn small" data-open="${safeText(order.id)}">पूरी जानकारी देखें और स्वीकार करें ↗</button></div></article>`;
  };
  render = function () {
    renderBeforeReceiveRestore();
    if (tab !== 'receive' || active) return;
    const content = document.querySelector('.content');
    if (!content) return;
    const posts = (state.orders || []).filter(order => order.kind !== 'delivery-service' && order.status === 'open' && order.owner !== user);
    content.innerHTML = `<section class="delivery-receive-page"><div class="receive-hero"><div class="bike-animation"><span class="bike-rider">🧑‍✈️</span><span class="bike">🛵</span><i></i><i></i><i></i></div><div><p class="eyebrow">DELIVERY RECEIVE</p><h1>नई delivery requests</h1><p>अपने आसपास की खुली मांग चुनें और delivery शुरू करें।</p></div></div><div class="market-list">${posts.map(requestCard).join('') || '<div class="empty">अभी कोई delivery request उपलब्ध नहीं है।</div>'}</div></section>`;
  };
  render();
}, 0);

