let editingOrderId=null;
const canEditOrder=o=>o&&o.owner===user&&['open','chat'].includes(o.status)&&!o.ownerDone&&!o.providerDone;
const editButton=o=>canEditOrder(o)?`<button class="btn edit-order-button" data-edit-order="${o.id}">✎ Edit करें</button>`:'';
const marketBeforeEdit=marketCard;
marketCard=function(o){return marketBeforeEdit(o)};
const cardBeforeEdit=card;
card=function(o){return cardBeforeEdit(o).replace('</article>',(tab==='orders'?editButton(o):'')+'</article>')};
const detailBeforeEdit=detail;
detail=function(){const o=state.orders.find(o=>o.id===active);return detailBeforeEdit()+(tab==='orders'?editButton(o):'')};
const renderBeforeEdit=render;
render=function(){renderBeforeEdit();if(!editingOrderId||tab!=='post')return;const o=state.orders.find(o=>o.id===editingOrderId);if(!canEditOrder(o)){editingOrderId=null;return}const f=document.getElementById('broadcastForm');if(!f)return;const info=requestSummary(o);const due=new Date(o.neededBy||'');const hasDue=!Number.isNaN(due.getTime());const localDate=hasDue?due.getFullYear()+'-'+String(due.getMonth()+1).padStart(2,'0')+'-'+String(due.getDate()).padStart(2,'0'):localDeliveryToday();const hour=hasDue?due.getHours():12;const localTime=String((hour%12)||12).padStart(2,'0')+':'+String(hasDue?due.getMinutes():0).padStart(2,'0');const values={title:o.title,description:String(o.description||'').replace(/\\n/g,'\n').split('\n').filter(line=>!line.startsWith('मात्रा:')&&!line.startsWith('कब तक चाहिए:')).join('\n'),quantity:info.quantity==='मात्रा नहीं बताई'?'':info.quantity,area:info.pickup,deliveryVillage:info.dropoff==='गांव नहीं बताया'?'':info.dropoff,district:o.district||'',address:o.address,neededDate:localDate,neededTime:localTime,neededMeridiem:hour>=12?'PM':'AM',category:o.category,items:o.items,fee:o.fee,neededBy:requirementTime(o)==='समय नहीं बताया'?'':requirementTime(o)};for(const [key,value] of Object.entries(values))f.elements[key].value=value??'';attachment=o.photo||null;document.querySelector('.post-page h1').textContent='अपना ऑर्डर Edit करें';f.querySelector('button[type=submit]').textContent='✓ बदलाव सेव करें';document.getElementById('postTotal').textContent=money(total(o));restoreOrderItems(f,o);if(o.photo){document.getElementById('attachmentName').textContent='पहले वाली फोटो लगी है';document.getElementById('attachmentHint').textContent='चाहें तो दूसरी फोटो चुनें'}if(o.status!=='open'){f.elements.items.readOnly=true;f.elements.fee.readOnly=true;const note=document.createElement('p');note.className='notice';note.textContent='रकम बदलने के लिए ऑर्डर की बातचीत में नया सुझाव भेजें। बाकी बदलाव डिलीवरी करने वाले को बातचीत में दिखेंगे।';f.elements.fee.closest('section').append(note)}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.editOrder){const o=state.orders.find(o=>o.id===b.dataset.editOrder);if(!canEditOrder(o))return;editingOrderId=o.id;if(typeof deliveryPostMode!=='undefined')deliveryPostMode='need';go('post');window.scrollTo({top:0,behavior:'smooth'});}else if(b.dataset.go||b.dataset.open||b.id==='logoutProfile'){editingOrderId=null}},true);
document.addEventListener('submit',async e=>{if(e.target.id!=='broadcastForm'||!editingOrderId)return;e.preventDefault();e.stopImmediatePropagation();const o=state.orders.find(o=>o.id===editingOrderId);if(!canEditOrder(o)){toast('यह ऑर्डर अब Edit नहीं हो सकता।');return}const f=e.target;if(!f.reportValidity())return;const d=new FormData(f),read=k=>String(d.get(k)||'').trim();const items=Number(d.get('items')),fee=Number(d.get('fee'));if(!['title','description','quantity','area','deliveryVillage','address'].every(k=>read(k))||!validMoney(items,fee)){toast('सभी जरूरी जानकारी और सही रकम भरें।');return}if(o.status!=='open'&&(items!==o.items||fee!==o.fee)){toast('रकम बदलने का सुझाव बातचीत में भेजें।');return}const lineItems=readOrderItems(f);if(!lineItems.length||lineItems.some(r=>!r.name||!r.quantity)){toast('हर सामान का नाम और Quantity भरें।');return}const summary=itemListSummary(lineItems);const previous=JSON.parse(JSON.stringify(o));const revisedTotal=items+fee;if(o.status==='open'&&DeliveryEngine.available(state,user)+(Number(o.customerHold)||0)<revisedTotal){showPostMoneyNeed(f,revisedTotal);toast('बढ़ी हुई रकम के लिए पहले पैसा ऐड करें।');return}Object.assign(o,{title:summary.title,description:read('description'),quantity:summary.quantity,lineItems,area:read('area'),deliveryVillage:read('deliveryVillage'),address:read('address'),neededBy:read('neededBy'),category:read('category'),items,fee,customerHold:o.status==='open'?revisedTotal:o.customerHold,photo:attachment});try{const raw=localStorage.getItem('aditya_studio_session_v1')||localStorage.getItem('aditya_studio_persistent_login_v2'),session=raw?JSON.parse(raw):null,res=await fetch('/api/local-delivery/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:session?.mobile,sessionToken:session?.sessionToken,action:'owner-edit',orderId:o.id,order:o})}),out=await res.json();if(!res.ok||!out.ok)throw Error(out.message||'Server save नहीं हुआ')}catch(err){Object.assign(o,previous);toast(err.message||'बदलाव सेव नहीं हुए।');return}if(o.provider){system(o,'मांग करने वाले ने ऑर्डर की जानकारी बदली: '+o.title+' | मात्रा: '+o.quantity+' | '+o.area+' → '+o.deliveryVillage+' | पता: '+o.address+' | समय: '+(o.neededBy||'नहीं बताया')+' | जानकारी: '+o.description)}try{localStorage.setItem(KEY,JSON.stringify(state))}catch{Object.assign(o,previous);toast('बदलाव सेव नहीं हुए। छोटी फोटो चुनकर कोशिश करें।');return}editingOrderId=null;attachment=null;tab='orders';active=o.id;render();toast('ऑर्डर के बदलाव सेव हो गए।')},true);
render();



