window.appLanguage='hi';
try{window.appLanguage=localStorage.getItem('local-delivery-language')||'hi'}catch{}
const englishText={
 'होम':'Home','मेरे ऑर्डर':'My orders','पोस्ट करें':'Post','वॉलेट':'Wallet','बातचीत':'Messages','आपके गांव का मददगार':'Your neighbourhood helper',
 'Location खोजें':'Search location','छत्तीसगढ़ · सभी पोस्ट':'Chhattisgarh · all posts','आसपास की जरूरतें':'Nearby requests','खुली मांगें':'open requests',
 'सभी':'All','राशन':'Groceries','सामान लाना':'Pickup','खरीदारी':'Shopping','अन्य':'Other','डिलीवरी की कमाई':'Delivery earning',
 'मेरे ऑर्डर में देखें':'View in my orders','देखें और स्वीकार करें':'View and accept','सामान और Quantity':'Items and quantity',
 'मेरी प्रोफ़ाइल':'My profile','आपकी जानकारी और आपके सभी ऑर्डर':'Your details and all your orders','पूरा नाम':'Full name','मोबाइल नंबर':'Mobile number','गांव / शहर':'Village / city','ऐप की भाषा':'App language','हिंदी':'Hindi','जानकारी बदलें':'Edit details','बदलाव बंद करें':'Close edit','जानकारी सेव करें':'Save details','सभी देखें →':'View all →','कुल ऑर्डर':'Total orders','चालू ऑर्डर':'Active orders','पूरे हुए':'Completed','लॉग आउट':'Log out','होम पर वापस जाएं':'Back to home',
 'आपका वॉलेट':'Your wallet','उपलब्ध रकम':'Available balance','रिज़र्व रकम:':'Reserved amount:','लेन-देन देखें ↗':'View transactions ↗','पैसा ऐड करें':'Add money','डेमो पैसे जोड़ें (₹)':'Add demo money (₹)','पैसे जोड़ें':'Add money','लेन-देन का हिसाब':'Transactions',
 'नई मांग':'New request','बातचीत जारी':'Chat active','बुक हो गया':'Booked','पुष्टि का इंतज़ार':'Awaiting confirmation','पूरा हुआ':'Completed','रद्द':'Cancelled',
 'आपको क्या मंगाना है?':'What do you need?','पूरी जानकारी भरें, ताकि सामान लाने वाले को सब साफ समझ आए।':'Add complete details so the delivery person understands clearly.','सामान की जानकारी':'Item details','Category / सामान का प्रकार':'Category / item type','और सामान जोड़ें':'Add another item','सामान की पूरी लिस्ट और जरूरी बातें *':'Complete item list and instructions *','सामान की फोटो लगाएं':'Add item photo','जरूरी नहीं · JPG, PNG, WebP · 1 MB तक':'Optional · JPG, PNG, WebP · up to 1 MB','फोटो जोड़ें':'Add photo',
 'कहां से लाना और पहुंचाना है?':'Pickup and delivery location','दुकान / बाजार / गांव का नाम *':'Shop / market / village name *','किस गांव / शहर में पहुंचाना है? *':'Delivery village / city *','सामान पहुंचाने का पूरा पता *':'Full delivery address *','यह पता आपकी मांग स्वीकार करने वाले को दिखेगा।':'This address is visible to the person who accepts your request.','कब तक चाहिए?':'Needed by?','कुल अनुमानित रकम':'Estimated total amount','अपनी मांग पोस्ट करें':'Post my request','ये जानकारी भरना जरूरी है। यह डेमो वेबसाइट है।':'These details are required. This is a demo website.',
 'सामान का नाम, मात्रा, ब्रांड या रंग लिखें। सामान न मिले तो विकल्प भी लिखें।':'Write item name, quantity, brand or colour. Add an alternative if unavailable.','जैसे: बाजार या दुकान का नाम':'Example: market or shop name','जैसे: गांव या शहर का नाम':'Example: village or city name','घर नंबर, गली, मोहल्ला और पास की पहचान':'House number, street, locality and nearby landmark','जैसे: आज शाम 5 बजे तक (जरूरी नहीं)':'Example: today by 5 PM (optional)','जैसे: 500':'Example: 500','जैसे: 80':'Example: 80',
 'सामान का नाम':'Item name','Quantity / कितना Kg?':'Quantity / how many kg?','मात्रा नहीं बताई':'Quantity not specified','सही रकम भरें':'Enter a valid amount','नई मांग पोस्ट करें':'Post new request','डिलीवरी से जुड़ी सभी बातचीत यहां देखें।':'See all delivery conversations here.','आपकी पोस्ट की गई मांगें और स्वीकार किए गए काम।':'Your posted requests and accepted jobs.',
 '＋ और सामान जोड़ें':'＋ Add another item','＋ अपनी मांग पोस्ट करें':'＋ Post my request','＋ नई मांग':'＋ New request','← होम पर वापस जाएं':'← Back to home','* ये जानकारी भरना जरूरी है। यह डेमो वेबसाइट है।':'* These details are required. This is a demo website.',
 'Kharch aur delivery charge':'Cost and delivery fee','Saman ki keemat (₹) *':'Item cost (₹) *','Saman lane ki rashi (₹) *':'Delivery fee (₹) *','Post करते ही कुल रकम wallet में lock होगी। Cancel करने पर रकम वापस wallet में unlock होगी। Helper accept होने पर सामान की कीमत जितना उसका deposit lock होगा।':'Your total is locked in the wallet when you post. It is unlocked on cancellation. The helper locks an item-cost deposit after accepting.'
};
function localizePage(){document.documentElement.lang=window.appLanguage==='en'?'en':'hi';if(window.appLanguage!=='en')return;const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{const text=n.nodeValue.trim();if(englishText[text])n.nodeValue=n.nodeValue.replace(text,englishText[text])});document.querySelectorAll('[placeholder],[aria-label],[title]').forEach(el=>{['placeholder','aria-label','title'].forEach(a=>{if(englishText[el.getAttribute(a)])el.setAttribute(a,englishText[el.getAttribute(a)])})})}
const languageRenderBefore=render;
render=function(){languageRenderBefore();localizePage()};
document.addEventListener('change',e=>{if(e.target.id!=='appLanguage')return;window.appLanguage=e.target.value;try{localStorage.setItem('local-delivery-language',window.appLanguage)}catch{}render()});
render();
