(function(){
  let map,marker,chosen; const startPoint=[21.8974,82.9878];
  function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.append(css);const script=document.createElement('script');script.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';script.onload=resolve;script.onerror=reject;document.head.append(script)})}
  async function json(url){const res=await fetch(url,{headers:{Accept:'application/json'}});if(!res.ok)throw Error('Location service unavailable');return res.json()}
  async function addressFor(lat,lng){try{const data=await json('https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat='+encodeURIComponent(lat)+'&lon='+encodeURIComponent(lng));return data.display_name||''}catch(_){return ''}}
  async function searchPlace(query){const data=await json('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=6&countrycodes=in&q='+encodeURIComponent(query));return Array.isArray(data)?data:[]}
  function escapeHtml(value){return String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
  function inject(){const form=document.getElementById('broadcastForm');if(!form||form.dataset.locationPicker)return;const village=form.elements.deliveryVillage;if(!village)return;form.dataset.locationPicker='1';const box=document.createElement('div');box.className='location-picker';box.innerHTML='<b>📍 Delivery location</b><small id="pickedLocationText">Map पर अपना exact घर / delivery location चुनें</small><button type="button" id="pickMapLocation">🗺️ Map पर location चुनें</button><input type="hidden" name="latitude"><input type="hidden" name="longitude"><input type="hidden" name="mapAddress">';village.closest('label').after(box);
    box.querySelector('#pickMapLocation').onclick=async()=>{const modal=document.createElement('div');modal.className='location-modal';modal.innerHTML='<div class="location-dialog"><div class="location-title"><b>📍 Delivery location चुनें</b><button type="button" id="closeMapLocation" aria-label="Close map">×</button></div><p>Search करें या map पर pin को खींचें / tap करें।</p><form class="map-search" id="mapSearchForm"><input id="mapSearchInput" autocomplete="street-address" placeholder="गांव, मोहल्ला या पूरा address खोजें"><button>🔎 खोजें</button></form><div class="gps-actions"><button type="button" class="current-location" id="useCurrentLocation">⌖ मेरी current location</button><button type="button" class="gps-refresh" id="refreshGps">↻ GPS refresh</button></div><div id="mapSearchResults" class="map-search-results" hidden></div><div id="deliveryLocationMap"></div><small id="locationAddress">Map से location चुनें या ऊपर search करें।</small><div class="location-actions"><button type="button" id="saveMapLocation">✓ यह location save करें</button><button type="button" id="cancelMapLocation">Cancel</button></div></div>';document.body.append(modal);const close=()=>modal.remove();modal.querySelector('#closeMapLocation').onclick=close;modal.querySelector('#cancelMapLocation').onclick=close;
      try{await loadLeaflet();map=L.map('deliveryLocationMap').setView(startPoint,12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);marker=L.marker(startPoint,{draggable:true}).addTo(map);const address=modal.querySelector('#locationAddress'),results=modal.querySelector('#mapSearchResults');async function set(pos,label){chosen={lat:Number(pos.lat),lng:Number(pos.lng),address:label||''};marker.setLatLng(chosen);map.setView(chosen,17);address.textContent='Address ढूंढा जा रहा है…';const resolved=label||await addressFor(chosen.lat,chosen.lng);if(chosen&&Number(chosen.lat)===Number(pos.lat)&&Number(chosen.lng)===Number(pos.lng)){chosen.address=resolved;address.textContent=resolved||('Pinned location: '+chosen.lat.toFixed(6)+', '+chosen.lng.toFixed(6))}}await set({lat:startPoint[0],lng:startPoint[1]});setTimeout(()=>map.invalidateSize(),80);map.on('click',e=>set(e.latlng));marker.on('dragend',e=>set(e.target.getLatLng()));
        const getGps=force=>{if(!navigator.geolocation){address.textContent='इस browser में GPS उपलब्ध नहीं है।';return}address.textContent=force?'GPS फिर से accurate location ढूंढ रहा है…':'GPS से current location ली जा रही है…';navigator.geolocation.getCurrentPosition(p=>{const accuracy=Math.round(Number(p.coords.accuracy||0));set({lat:p.coords.latitude,lng:p.coords.longitude}).then(()=>{address.textContent=(chosen.address||'Current GPS location')+(accuracy?' · accuracy ±'+accuracy+'m':'')})},()=>{address.textContent='GPS location नहीं मिली। Phone location/GPS और browser permission चालू करके GPS refresh दबाएं।'},{enableHighAccuracy:true,timeout:25000,maximumAge:force?0:30000})};modal.querySelector('#useCurrentLocation').onclick=()=>getGps(false);modal.querySelector('#refreshGps').onclick=()=>getGps(true);const gpsControl=L.control({position:'topleft'});gpsControl.onAdd=()=>{const control=L.DomUtil.create('button','leaflet-gps-control');control.type='button';control.title='मेरी current GPS location';control.setAttribute('aria-label','मेरी current GPS location');control.textContent='⌖';L.DomEvent.disableClickPropagation(control);L.DomEvent.on(control,'click',()=>getGps(true));return control};gpsControl.addTo(map);getGps(false);
        modal.querySelector('#mapSearchForm').onsubmit=async e=>{e.preventDefault();const query=modal.querySelector('#mapSearchInput').value.trim();if(query.length<3){address.textContent='कम से कम 3 अक्षर लिखकर search करें।';return}address.textContent='Location search हो रही है…';results.hidden=true;results.innerHTML='';try{const places=await searchPlace(query);if(!places.length){address.textContent='यह location नहीं मिली। दूसरे शब्दों से search करें।';return}results.innerHTML=places.map((place,i)=>'<button type="button" data-place="'+i+'"><b>'+escapeHtml(place.display_name||'Location')+'</b></button>').join('');results.hidden=false;places.forEach((place,i)=>results.querySelector('[data-place="'+i+'"]').onclick=()=>{results.hidden=true;set({lat:place.lat,lng:place.lon},place.display_name||'')})}catch(_){address.textContent='Search नहीं हुई। Internet check करके फिर try करें।'}};
        modal.querySelector('#saveMapLocation').onclick=()=>{if(!chosen)return;form.elements.latitude.value=chosen.lat;form.elements.longitude.value=chosen.lng;form.elements.mapAddress.value=chosen.address||'';box.querySelector('#pickedLocationText').textContent=chosen.address||('Location saved: '+chosen.lat.toFixed(5)+', '+chosen.lng.toFixed(5));if(chosen.address&&form.elements.address)form.elements.address.value=chosen.address;close()}
      }catch(_){modal.querySelector('.location-dialog').innerHTML='<b>Map load नहीं हुआ</b><p>Internet चालू करके फिर कोशिश करें।</p><button type="button" onclick="this.closest(\'.location-modal\').remove()">Close</button>'}}
  }
  new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',inject);setTimeout(inject,0);
})();