/* Private Marketplace threads inside the Local Delivery बातचीत tab. */
(function(){
  const before=render, escHub=x=>String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const marketCss='.market-card{width:100%;text-align:left;margin:10px 0;padding:14px;border:1px solid #33518a;border-radius:14px;background:#121d35;color:#eef5ff}.market-card b{display:block;font-size:16px;color:#60f0c0}.market-card small{display:block;color:#a8b8d8;margin-top:5px}.market-chat{position:fixed!important;inset:0!important;z-index:9999!important;display:flex!important;flex-direction:column!important;height:100vh!important;background:#070d1c!important}.market-chat-head{display:flex;align-items:center;gap:12px;padding:14px 16px;border-bottom:1px solid #30486f;background:#121d35}.market-back{border:0;background:#25385d;color:#fff;border-radius:10px;padding:9px 12px}.market-avatar{background:linear-gradient(135deg,#7041ff,#2496ff);width:42px;height:42px;display:grid;place-items:center;border-radius:50%;font-size:19px;color:#fff}.market-chat-head b{font-size:17px;color:#fff}.market-chat-head small{display:block;color:#9eafd0;margin-top:3px}.market-item{padding:11px 16px;background:#101d37;color:#62eac0;border-bottom:1px solid #30486f;font-weight:bold}.market-bubbles{flex:1!important;padding:18px 15px!important;overflow-y:auto!important;background:#080e1c}.market-bubble{max-width:76%;width:max-content;padding:10px 13px;margin:10px 0;border-radius:17px 17px 17px 4px;background:#172742;color:#f7fbff;box-shadow:0 2px 8px #0005;line-height:1.4}.market-name{display:block;color:#62eaff;font-size:12px;margin-bottom:4px;font-weight:800}.market-bubble.mine{margin-left:auto;border-radius:17px 17px 4px 17px;background:linear-gradient(135deg,#6d2ce9,#386cff);text-align:right}.market-bubble.mine .market-name{color:#fff289}.market-bubble small{display:block;color:#d8e3ff;font-size:10px;margin-top:5px}.market-compose{display:flex!important;gap:8px!important;padding:10px 12px!important;border-top:1px solid #30486f!important;background:#111b31!important;margin-top:auto!important;padding-bottom:max(10px,env(safe-area-inset-bottom))!important}.market-compose input{flex:1!important;margin:0!important;min-height:44px!important}.market-compose button{border:0!important;border-radius:12px!important;background:#6d35ef!important;color:#fff!important;font-weight:bold!important;padding:0 18px!important;min-width:54px!important}'; function ensureStyle(){if(document.getElementById('market-chat-styles'))return;const style=document.createElement('style');style.id='market-chat-styles';style.textContent=marketCss;document.head.append(style)};
  let threads=[],openKey='',lastLoad=0,loading=false;try{const u=new URLSearchParams(location.search),id=u.get('marketChat'),peer=u.get('peer');if(id){openKey=String(id)+'|'+String(peer||'');tab='messages';history.replaceState({},'',location.pathname)}}catch(_){}
  const session=()=>{try{return JSON.parse(localStorage.getItem('aditya_studio_session_v1')||localStorage.getItem('aditya_studio_persistent_login_v2')||'null')}catch(_){return null}};
  const key=t=>String(t.id)+'|'+String(t.peerMobile||'');
  async function loadMarket(force=false){const s=session();if(!s?.sessionToken||loading||(!force&&Date.now()-lastLoad<6000))return;loading=true;try{const r=await fetch('/api/marketplace-inbox?sessionToken='+encodeURIComponent(s.sessionToken)),d=await r.json();if(r.ok&&d.ok){const next=Array.isArray(d.threads)?d.threads:[];if(JSON.stringify(next)!==JSON.stringify(threads)){threads=next;if(tab==='messages'&&!active)render()}lastLoad=Date.now()}}catch(_){}finally{loading=false}}
  function threadList(){return `<section class="notifications-page market-inbox"><div class="notification-heading"><span>💬</span><div><h1>मेरी बातचीत</h1><p>Delivery और Marketplace की private बातचीत</p></div></div><div class="notification-list">${threads.length?`<h3>🛒 Marketplace Inbox</h3>${threads.map(t=>`<button class="market-card" data-market-open="${escHub(key(t))}"><b>🛒 ${escHub(t.title||'Marketplace item')}</b><small>💬 ${escHub(t.peerName||'User')} · Tap करके chat खोलें</small></button>`).join('')}`:'<div class="empty">अभी कोई private बातचीत नहीं है।</div>'}</div></section>`}
  function chatView(t){const s=session(),mine=String(s?.mobile||'').replace(/\D/g,'').slice(-10);return `<section class="market-chat"><header class="market-chat-head"><button class="market-back" data-market-close>←</button><span class="market-avatar">${escHub(String(t.peerName||'U')[0].toUpperCase())}</span><div><b>${escHub(t.peerName||'Marketplace user')}</b><small>○ Offline · Private marketplace chat</small></div></header><div class="market-item">🛒 ${escHub(t.title||'Marketplace item')}</div><main class="market-bubbles">${(t.messages||[]).map(m=>`<div class="market-bubble ${String(m.senderMobile||'').replace(/\D/g,'').slice(-10)===mine?'mine':''}"><b class="market-name">${escHub(m.senderName||'User')}</b>${escHub(m.text)}<small>${escHub(m.time||'')}</small></div>`).join('')||'<p class="empty">Message शुरू करें।</p>'}</main><form class="market-compose" data-market-form data-market-id="${escHub(t.id)}" data-market-peer="${escHub(t.peerMobile)}"><input name="text" maxlength="1000" placeholder="Message लिखें…" required><button>➤</button></form></section>`}
  render=function(){ensureStyle();before();if(tab!=='messages'||active)return;const current=threads.find(t=>key(t)===openKey);document.querySelector('.content').innerHTML=current?chatView(current):threadList();loadMarket()};
  document.addEventListener('click',e=>{const open=e.target.closest('[data-market-open]'),close=e.target.closest('[data-market-close]');if(open){openKey=open.dataset.marketOpen;render()}if(close){openKey='';render()}});
  document.addEventListener('submit',async e=>{const f=e.target.closest('[data-market-form]');if(!f)return;e.preventDefault();const s=session(),text=String(new FormData(f).get('text')||'').trim();if(!s?.sessionToken||!text)return;const b=f.querySelector('button');b.disabled=true;try{const r=await fetch('/api/used-listing-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:f.dataset.marketId,peerMobile:f.dataset.marketPeer,text,sessionToken:s.sessionToken})}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.message||'Message नहीं गया');f.reset();lastLoad=0;await loadMarket(true)}catch(err){alert(err.message||'Message नहीं गया')}finally{b.disabled=false}});
  render();setInterval(()=>{if(tab==='messages'&&!active)loadMarket(true)},7000);
})();
