let profileEditing=false;
let demoLoggedOut=false;
try{demoLoggedOut=sessionStorage.getItem('kaamsetu-logged-out')==='yes'}catch{}
function profilePage(){const u=state.users[user],orders=state.orders.filter(mine),completed=orders.filter(o=>o.status==='completed').length;return `<section class="user-profile"><button class="back" data-go="home">← होम पर वापस जाएं</button><div class="profile-heading"><div class="profile-portrait" aria-label="यूज़र की प्रोफ़ाइल">${esc(u.name.trim().charAt(0).toUpperCase())}</div><h1>मेरी प्रोफ़ाइल</h1><p>आपकी जानकारी और आपके सभी ऑर्डर</p></div><div class="profile-details"><div class="profile-field name-field"><span class="profile-glyph">♙</span><div><small>पूरा नाम</small><strong>${esc(u.name)}</strong></div></div><div class="profile-field phone-field"><span class="profile-glyph">☎</span><div><small>मोबाइल नंबर</small><strong>${esc(u.phone||'मोबाइल नंबर जोड़ें')}</strong></div></div><div class="profile-field village-field"><span class="profile-glyph">⌖</span><div><small>गांव / शहर</small><strong>${esc(u.village||'अपने गांव का नाम जोड़ें')}</strong></div></div><label class="profile-language"><span>◉</span><div><small>ऐप की भाषा</small><select id="appLanguage"><option value="hi" ${window.appLanguage!=='en'?'selected':''}>हिंदी</option><option value="en" ${window.appLanguage==='en'?'selected':''}>English</option></select></div></label><button class="profile-edit" id="editProfile">✎ ${profileEditing?'बदलाव बंद करें':'जानकारी बदलें'}</button>${profileEditing?`<form id="profileForm"><label>पूरा नाम<input name="name" required maxlength="80" value="${esc(u.name)}" autocomplete="name"></label><label>मोबाइल नंबर<input name="phone" type="tel" inputmode="numeric" pattern="[6-9][0-9]{9}" maxlength="10" required placeholder="10 अंकों का मोबाइल नंबर" value="${esc(u.phone||'')}" autocomplete="tel-national"></label><label>गांव / शहर<input name="village" required maxlength="100" placeholder="अपने गांव का नाम" value="${esc(u.village||'')}" autocomplete="address-level2"></label><button class="btn" type="submit">जानकारी सेव करें</button></form>`:''}</div><section class="profile-orders"><div class="row"><h2>▤ मेरे ऑर्डर</h2><button class="profile-edit" data-go="orders">सभी देखें →</button></div><div class="profile-order-stats"><div><strong>${orders.length}</strong><span>कुल ऑर्डर</span></div><div><strong>${orders.filter(o=>!['completed','cancelled'].includes(o.status)).length}</strong><span>चालू ऑर्डर</span></div><div><strong>${completed}</strong><span>पूरे हुए</span></div></div>${orders.slice(0,3).map(o=>`<button class="profile-order" data-open="${o.id}"><span><strong>${esc(o.title)}</strong><small>${o.owner===user?'आपकी मांग':'आपने स्वीकार किया'} · ${money(total(o))}</small></span>${badge(o)}</button>`).join('')||'<p class="muted">अभी आपका कोई ऑर्डर नहीं है।</p>'}</section><button class="profile-logout" id="logoutProfile">↪ &nbsp; लॉग आउट</button><p class="profile-demo-note">प्रोफ़ाइल की जानकारी आपके इस device पर सुरक्षित सेव रहती है।</p></section>`}
const renderBeforeProfile=render;
render=function(){if(demoLoggedOut){document.getElementById('app').innerHTML=`<main class="demo-signout"><div class="profile-portrait">✓</div><h1>आप लॉग आउट हो गए हैं</h1><p>आपके ऑर्डर और वॉलेट की डेमो जानकारी सेव है।</p><button class="btn" id="loginDemo">डेमो में वापस जाएं</button><small>यह स्थानीय डेमो है। असली लॉगिन अभी जुड़ा नहीं है।</small></main>`;return}renderBeforeProfile();if(tab==='profile'&&!active)document.querySelector('.content').innerHTML=profilePage()};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='editProfile'){profileEditing=!profileEditing;render()}if(b.id==='logoutProfile'){demoLoggedOut=true;profileEditing=false;active=null;try{sessionStorage.setItem('kaamsetu-logged-out','yes')}catch{}render()}if(b.id==='loginDemo'){demoLoggedOut=false;try{sessionStorage.removeItem('kaamsetu-logged-out')}catch{}go('home')}});
document.addEventListener('submit',e=>{if(e.target.id!=='profileForm')return;e.preventDefault();const d=new FormData(e.target),name=d.get('name').trim(),phone=d.get('phone').trim(),village=d.get('village').trim();if(!name||!village||! /^[6-9][0-9]{9}$/.test(phone)){toast('नाम, गांव और सही 10 अंकों का मोबाइल नंबर भरें।');return}const previous={...state.users[user]};Object.assign(state.users[user],{name,phone,village});try{localStorage.setItem(KEY,JSON.stringify(state))}catch{state.users[user]=previous;toast('जानकारी सेव नहीं हुई। ब्राउज़र की जगह जांचें।');return}profileEditing=false;render();toast('आपकी प्रोफ़ाइल सेव हो गई।')});
render();
