package store.adityastudio.deliverymanage;

import android.app.*; import android.content.*; import android.graphics.Color; import android.graphics.PixelFormat; import android.os.*; import android.provider.Settings; import android.view.*; import android.widget.*; import androidx.core.content.ContextCompat; import androidx.core.app.NotificationCompat; import java.util.Map;

public class DeliveryOnlineService extends Service {
  static final String PREF="delivery_online", ONLINE="online", ACTION_SHOW="SHOW_ORDER", ACTION_START="START"; static final int STATUS_ID=731;
  WindowManager wm; View overlay; Handler handler=new Handler(Looper.getMainLooper());
  public static boolean isOnline(Context c){return c.getSharedPreferences(PREF,0).getBoolean(ONLINE,false);} 
  public static void start(Context c){c.getSharedPreferences(PREF,0).edit().putBoolean(ONLINE,true).apply();ContextCompat.startForegroundService(c,new Intent(c,DeliveryOnlineService.class).setAction(ACTION_START));}
  public static void stop(Context c){c.getSharedPreferences(PREF,0).edit().putBoolean(ONLINE,false).apply();c.stopService(new Intent(c,DeliveryOnlineService.class));}
  public static void showOrder(Context c,Map<String,String> d){if(!isOnline(c))return;Intent i=new Intent(c,DeliveryOnlineService.class).setAction(ACTION_SHOW);for(Map.Entry<String,String> e:d.entrySet())i.putExtra(e.getKey(),e.getValue());ContextCompat.startForegroundService(c,i);}
  @Override public void onCreate(){super.onCreate();wm=(WindowManager)getSystemService(WINDOW_SERVICE);createChannel();startForeground(STATUS_ID,status());}
  @Override public int onStartCommand(Intent i,int flags,int id){if(i!=null&&ACTION_SHOW.equals(i.getAction())&&Settings.canDrawOverlays(this))show(i);return START_STICKY;}
  Notification status(){return new NotificationCompat.Builder(this,"delivery_online_status").setSmallIcon(getApplicationInfo().icon).setContentTitle("Delivery Manage: Online").setContentText("नया order आने पर popup दिखेगा").setOngoing(true).setPriority(NotificationCompat.PRIORITY_LOW).build();}
  void createChannel(){if(Build.VERSION.SDK_INT<26)return;NotificationManager n=getSystemService(NotificationManager.class);n.createNotificationChannel(new NotificationChannel("delivery_online_status","Delivery boy online status",NotificationManager.IMPORTANCE_LOW));}
  TextView tv(String s,int size){TextView x=new TextView(this);x.setText(s);x.setTextSize(size);x.setTextColor(Color.WHITE);x.setPadding(dp(14),dp(8),dp(14),dp(8));return x;}int dp(int x){return(int)(x*getResources().getDisplayMetrics().density);}
  void show(Intent in){remove();LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(8),dp(12),dp(8),dp(16));card.setBackgroundColor(Color.rgb(12,25,54));card.addView(tv("🔔 NEW DELIVERY REQUEST",13));TextView title=tv(in.getStringExtra("title"),21);title.setTextColor(Color.rgb(110,231,183));card.addView(title);card.addView(tv("🏪 Pickup: "+in.getStringExtra("pickup"),16));card.addView(tv("📍 Drop: "+in.getStringExtra("drop"),16));TextView earn=tv("💸 Earning: ₹"+in.getStringExtra("earning"),19);earn.setTextColor(Color.rgb(253,230,138));card.addView(earn);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);TextView no=tv("✕ DECLINE",15),yes=tv("✓ ACCEPT ORDER",15);no.setGravity(Gravity.CENTER);yes.setGravity(Gravity.CENTER);no.setBackgroundColor(Color.rgb(185,28,28));yes.setBackgroundColor(Color.rgb(5,150,105));row.addView(no,new LinearLayout.LayoutParams(0,dp(52),1));row.addView(yes,new LinearLayout.LayoutParams(0,dp(52),1));card.addView(row);no.setOnClickListener(v->remove());yes.setOnClickListener(v->{Intent app=new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);app.putExtra("orderId",in.getStringExtra("orderId"));startActivity(app);remove();});WindowManager.LayoutParams lp=new WindowManager.LayoutParams(-1,-2,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN|WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON,PixelFormat.TRANSLUCENT);lp.gravity=Gravity.TOP;lp.y=dp(24);overlay=card;wm.addView(overlay,lp);handler.postDelayed(this::remove,30000);}
  void remove(){handler.removeCallbacksAndMessages(null);if(overlay!=null){try{wm.removeView(overlay);}catch(Exception e){}overlay=null;}}
  @Override public void onDestroy(){remove();super.onDestroy();} @Override public android.os.IBinder onBind(Intent i){return null;}
}
